# Copyright 2025 Nutanix. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

apiVersion: controlplane.cluster.x-k8s.io/v1beta1
kind: KubeadmControlPlaneTemplate
metadata:
  name: not-used
spec:
  template:
    spec:
      kubeadmConfigSpec:
        clusterConfiguration:
          apiServer:
            extraArgs:
              # 1.2.15 Ensure that the --profiling argument is set to false
              profiling: "false"
              # 1.2.21 Ensure that the --service-account-lookup argument is set to true
              service-account-lookup: "true"
              # 1.2.3 Ensure that the DenyServiceExternalIPs is set
              # 1.2.9 Ensure that the admission control plugin EventRateLimit is set
              # 1.2.14 Ensure that the admission control plugin NodeRestriction is set
              enable-admission-plugins: DenyServiceExternalIPs,EventRateLimit,NodeRestriction
          controllerManager:
            extraArgs:
              #1.3.1 Ensure that the --terminated-pod-gc-threshold argument is set as appropriate
              terminated-pod-gc-threshold: "10000"
              #1.3.2 Ensure that the --profiling argument is set to false
              profiling: "false"
          scheduler:
            extraArgs:
              #1.4.1 Ensure that the --profiling argument is set to false
              profiling: "false"
