storageClass:
  create: false
  provisionerName: rancher.io/local-path
helperImage:
  tag: 1.36.1
tolerations:
  - key: CriticalAddonsOnly
    operator: Exists
  - effect: NoExecute
    operator: Exists
    tolerationSeconds: 300
  - effect: NoSchedule
    operator: Exists
