// Copyright 2024 Nutanix. All rights reserved.
// SPDX-License-Identifier: Apache-2.0
// Code generated by script; DO NOT EDIT. Run 'make coredns.sync' instead

package versions

// Kubernetes versions
const (
	Kubernetes_V1_22 = "1.22"
	Kubernetes_V1_23 = "1.23"
	Kubernetes_V1_24 = "1.24"
	Kubernetes_V1_25 = "1.25"
	Kubernetes_V1_26 = "1.26"
	Kubernetes_V1_27 = "1.27"
	Kubernetes_V1_28 = "1.28"
	Kubernetes_V1_29 = "1.29"
	Kubernetes_V1_30 = "1.30"
	Kubernetes_V1_31 = "1.31"
)

// CoreDNS versions
const (
	CoreDNS_V1_8_4  = "v1.8.4"
	CoreDNS_V1_8_6  = "v1.8.6"
	CoreDNS_V1_9_3  = "v1.9.3"
	CoreDNS_V1_10_1 = "v1.10.1"
	CoreDNS_V1_11_1 = "v1.11.1"
	CoreDNS_V1_11_3 = "v1.11.3"
)

// kubernetesToCoreDNSVersion maps Kubernetes versions to CoreDNS versions.
var kubernetesToCoreDNSVersion = map[string]string{
	Kubernetes_V1_22: CoreDNS_V1_8_4,
	Kubernetes_V1_23: CoreDNS_V1_8_6,
	Kubernetes_V1_24: CoreDNS_V1_8_6,
	Kubernetes_V1_25: CoreDNS_V1_9_3,
	Kubernetes_V1_26: CoreDNS_V1_9_3,
	Kubernetes_V1_27: CoreDNS_V1_10_1,
	Kubernetes_V1_28: CoreDNS_V1_10_1,
	Kubernetes_V1_29: CoreDNS_V1_11_1,
	Kubernetes_V1_30: CoreDNS_V1_11_3,
	Kubernetes_V1_31: CoreDNS_V1_11_3,
}

// GetCoreDNSVersion returns the CoreDNS version for a given Kubernetes version.
// If the Kubernetes version is not found, it returns an empty string and false.
func GetCoreDNSVersion(kubernetesVersion string) (string, bool) {
	version, found := kubernetesToCoreDNSVersion[kubernetesVersion]
	return version, found
}

// GetKubernetesToCoreDNSVersionMap returns a copy of the Kubernetes to CoreDNS version mapping.
func GetKubernetesToCoreDNSVersionMap() map[string]string {
	copyMap := make(map[string]string, len(kubernetesToCoreDNSVersion))
	for k, v := range kubernetesToCoreDNSVersion {
		copyMap[k] = v
	}

	return copyMap
}
