# Copyright 2025 Nutanix. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

version: "2"
run:
  build-tags:
    - e2e
linters:
  default: none
  enable:
    - containedctx
    - contextcheck
    - depguard
    - errcheck
    - errchkjson
    - errname
    - gochecknoinits
    - goconst
    - gocritic
    - gocyclo
    - godot
    - gosec
    - govet
    - importas
    - ineffassign
    - lll
    - misspell
    - nolintlint
    - prealloc
    - staticcheck
    - testifylint
    - thelper
    - tparallel
    - unconvert
    - unparam
    - unused
    - usetesting
    - whitespace
  settings:
    depguard:
      rules:
        main:
          list-mode: lax
          deny:
            - pkg: k8s.io/kubernetes
              desc: do not use k8s.io/kubernetes directly
            - pkg: sigs.k8s.io/cluster-api-provider-
              desc: do not use CAPI providers directly, instead vendor necessary APIs
            - pkg: sigs.k8s.io/cluster-api-addon-provider-
              desc: do not use CAPI providers directly, instead vendor necessary APIs
    errcheck:
      exclude-functions:
        - encoding/json.Marshal
        - encoding/json.MarshalIndent
    errchkjson:
      check-error-free-encoding: true
    gocritic:
      enabled-tags:
        - diagnostic
        - experimental
        - opinionated
        - performance
        - style
    importas:
      alias:
        - pkg: sigs.k8s.io/cluster-api/api/v1beta1
          alias: clusterv1
      no-unaliased: false
    lll:
      line-length: 120
    staticcheck:
      dot-import-whitelist:
        - github.com/onsi/ginkgo/v2
        - github.com/onsi/gomega
    testifylint:
      enable-all: true
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - errcheck
        source: flags.Parse|response.WriteError
      - linters:
          - lll
        source: '// \+kubebuilder:'
      - linters:
          - gocritic
        text: 'hugeParam: holderRef is heavy'
      - linters:
          - gocritic
        path: pkg/webhook
        text: 'hugeParam: req is heavy'
      - linters:
          - gocritic
        path: internal/test/envtest
        text: 'hugeParam: webhookInstallOptions is heavy'
      - linters:
          - gocritic
        path: internal/test/envtest
        text: 'hugeParam: input is heavy'
    paths:
      - external
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gci
    - gofumpt
    - golines
  settings:
    gci:
      sections:
        - Standard
        - Default
        - Prefix(github.com/nutanix-cloud-native)
        - Prefix(github.com/nutanix-cloud-native/cluster-api-runtime-extensions-nutanix)
    gofumpt:
      extra-rules: true
    golines:
      max-len: 120
  exclusions:
    generated: lax
    paths:
      - external
      - third_party$
      - builtin$
      - examples$
