# Copyright 2024 Nutanix. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

apiVersion: clusterctl.cluster.x-k8s.io/v1alpha3
kind: Metadata
releaseSeries:
  - contract: v1beta1
    major: 0
    minor: 2
  - contract: v1beta1
    major: 0
    minor: 3
  - contract: v1beta1
    major: 0
    minor: 4
  - contract: v1beta1
    major: 0
    minor: 5
  - contract: v1beta1
    major: 0
    minor: 6
  - contract: v1beta1
    major: 0
    minor: 7
  - contract: v1beta1
    major: 0
    minor: 8
  - contract: v1beta1
    major: 0
    minor: 9
  - contract: v1beta1
    major: 0
    minor: 10
  - contract: v1beta1
    major: 0
    minor: 11
  - contract: v1beta1
    major: 0
    minor: 12
  - contract: v1beta1
    major: 0
    minor: 13
  - contract: v1beta1
    major: 0
    minor: 14
  - contract: v1beta1
    major: 0
    minor: 15
  - contract: v1beta1
    major: 0
    minor: 16
  - contract: v1beta1
    major: 0
    minor: 17
  - contract: v1beta1
    major: 0
    minor: 18
  - contract: v1beta1
    major: 0
    minor: 19
  - contract: v1beta1
    major: 0
    minor: 20
  - contract: v1beta1
    major: 0
    minor: 21
  - contract: v1beta1
    major: 0
    minor: 22
  - contract: v1beta1
    major: 0
    minor: 23
  - contract: v1beta1
    major: 0
    minor: 24
  - contract: v1beta1
    major: 0
    minor: 25
  - contract: v1beta1
    major: 0
    minor: 26
  - contract: v1beta1
    major: 0
    minor: 27
  - contract: v1beta1
    major: 0
    minor: 28
  - contract: v1beta1
    major: 0
    minor: 29
  - contract: v1beta1
    major: 0
    minor: 30
  - contract: v1beta1
    major: 0
    minor: 31
  - contract: v1beta1
    major: 0
    minor: 32
  - contract: v1beta1
    major: 0
    minor: 33
  - contract: v1beta1
    major: 0
    minor: 34
  - contract: v1beta1
    major: 0
    minor: 35
  - contract: v1beta1
    major: 0
    minor: 36
  - contract: v1beta1
    major: 0
    minor: 37
  - contract: v1beta1
    major: 0
    minor: 38
