# Copyright 2024 Nutanix. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

- op: "add"
  path: "/spec/topology/variables/0/value/addons/csi/providers/local-path/strategy"
  value: ClusterResourceSet
- op: "add"
  path: "/spec/topology/variables/0/value/addons/csi/snapshotController/strategy"
  value: ClusterResourceSet
