# Copyright 2024 Nutanix. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

- op: "add"
  path: "/spec/topology/variables/0/value/addons/csi"
  value:
    defaultStorage:
      provider: local-path
      storageClassConfig: default
    providers:
      local-path:
        storageClassConfigs:
          default: {}
    snapshotController: {}
