{{- if .Values.hooks.cni.calico.helmAddonStrategy.defaultValueTemplatesConfigMaps.DockerCluster.create }}
apiVersion: v1
data:
  values.yaml: |2

    installation:
      cni:
        type: Calico
      calicoNetwork:
        ipPools:{{ printf "{{ range $cidr := .Cluster.spec.clusterNetwork.pods.cidrBlocks }}" }}
        - cidr: {{ printf "{{ $cidr }}" }}
          encapsulation: None
          natOutgoing: Enabled
          nodeSelector: all(){{ printf "{{ end }}" }}
      nodeMetricsPort: 9091
      typhaMetricsPort: 9093
      registry: quay.io/
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: '{{.Values.hooks.cni.calico.helmAddonStrategy.defaultValueTemplatesConfigMaps.DockerCluster.name}}'
{{- end -}}
