master:
  extraLabelNs:
    - nvidia.com
    - beta.amd.com
    - amd.com
  tolerations:
    - key: "node-role.kubernetes.io/control-plane"
      operator: "Equal"
      value: ""
      effect: "NoSchedule"
  affinity:
    nodeAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
        - weight: 1
          preference:
            matchExpressions:
              - key: "node-role.kubernetes.io/control-plane"
                operator: In
                values: [""]

worker: ### <NFD-WORKER-CONF-START-DO-NOT-REMOVE>
  config:
    sources:
      pci:
        deviceLabelFields:
          - "class"
          - "vendor"
  tolerations:
    - effect: NoSchedule
      key: node-role.kubernetes.io/control-plane

gc:
  tolerations:
    - effect: NoSchedule
      key: node-role.kubernetes.io/control-plane
