# Copyright 2025 Nutanix. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

apiVersion: v1
data:
  values.yaml: |-
    cni:
      exclusive: false
    hubble:
      enabled: true
      tls:
        auto:
          enabled: true               # enable automatic TLS certificate generation
          method: cronJob             # auto generate certificates using cronJob method
          certValidityDuration: 60    # certificates validity duration in days (default 2 months)
          schedule: "0 0 1 * *"       # schedule on the 1st day regeneration of each month
      relay:
        enabled: true
        tls:
          server:
            enabled: true
            mtls: true
        image:
          useDigest: false
        priorityClassName: system-cluster-critical
    image:
      useDigest: false
    operator:
      image:
        useDigest: false
    certgen:
      image:
        useDigest: false
    socketLB:
      hostNamespaceOnly: true
    envoy:
      image:
        useDigest: false
    kubeProxyReplacement: true
    k8sServiceHost: "{{ trimPrefix "https://" .Cluster.spec.controlPlaneEndpoint.host }}"
    k8sServicePort: "{{ .Cluster.spec.controlPlaneEndpoint.port }}"
    ipam:
      mode: eni
    enableIPv4Masquerade: false
    eni:
      enabled: true
      awsReleaseExcessIPs: true
    routingMode: native
    endpointRoutes:
      enabled: true
kind: ConfigMap
metadata:
  labels:
    cluster.x-k8s.io/provider: eks
  name: ${CLUSTER_NAME}-cilium-cni-helm-values-template
