# Copyright 2024 Nutanix. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

{{- if .Values.hooks.cni.cilium.helmAddonStrategy.defaultValueTemplateConfigMap.create }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: '{{ .Values.hooks.cni.cilium.helmAddonStrategy.defaultValueTemplateConfigMap.name }}'
data:
  values.yaml: |-
    {{- .Files.Get "addons/cni/cilium/values-template.yaml" | nindent 4 }}
{{- end -}}
