# Copyright 2023 Nutanix. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

{{- if .Values.hooks.cni.calico.helmAddonStrategy.defaultValueTemplatesConfigMaps.DockerCluster.create }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: '{{ .Values.hooks.cni.calico.helmAddonStrategy.defaultValueTemplatesConfigMaps.DockerCluster.name }}'
data:
  values.yaml: |-
    {{- .Files.Get "addons/cni/calico/docker/values-template.yaml" | nindent 4 }}
{{- end -}}
