controller:
  tolerations:
    - key: CriticalAddonsOnly
      operator: Exists
    - effect: NoExecute
      operator: Exists
      tolerationSeconds: 300
    - effect: NoSchedule
      operator: Exists
node:
  priorityClassName: system-node-critical
sidecars:
  snapshotter:
    forceEnable: true
