apiVersion: v1
data:
  values.yaml: |-
    cni:
      exclusive: false
    hubble:
      enabled: true
      tls:
        auto:
          enabled: true               # enable automatic TLS certificate generation
          method: cronJob             # auto generate certificates using cronJob method
          certValidityDuration: 60    # certificates validity duration in days (default 2 months)
          schedule: "0 0 1 * *"       # schedule on the 1st day regeneration of each month
      relay:
        enabled: true
        tls:
          server:
            enabled: true
            mtls: true
        image:
          useDigest: false
        priorityClassName: system-cluster-critical
    image:
      useDigest: false
    operator:
      image:
        useDigest: false
    certgen:
      image:
        useDigest: false
    socketLB:
      hostNamespaceOnly: true
    envoy:
      image:
        useDigest: false
    kubeProxyReplacement: true
    k8sServiceHost: "{{ trimPrefix "https://" .Cluster.spec.controlPlaneEndpoint.host }}"
    k8sServicePort: "{{ .Cluster.spec.controlPlaneEndpoint.port }}"
    ipam:
      mode: eni
    enableIPv4Masquerade: false
    eni:
      enabled: true
      awsReleaseExcessIPs: true
    routingMode: native
    endpointRoutes:
      enabled: true
kind: ConfigMap
metadata:
  name: ${CLUSTER_NAME}-cilium-cni-helm-values-template
---
apiVersion: cluster.x-k8s.io/v1beta1
kind: Cluster
metadata:
  name: ${CLUSTER_NAME}
  annotations:
    preflight.cluster.caren.nutanix.com/skip: all
spec:
  topology:
    class: eks-quick-start
    version: ${KUBERNETES_VERSION}
    variables:
      - name: clusterConfig
        value:
          addons:
            cni:
              provider: Cilium
              values:
                sourceRef:
                  name: ${CLUSTER_NAME}-cilium-cni-helm-values-template
                  kind: ConfigMap
    controlPlane:
      metadata:
        annotations:
          controlplane.cluster.x-k8s.io/skip-kube-proxy: ""
    workers:
      machineDeployments:
        - class: default-worker
          name: md-0
          replicas: ${WORKER_MACHINE_COUNT}
          variables:
            overrides:
              - name: workerConfig
                value:
                  eks:
                    instanceType: m5.2xlarge
