# Copyright 2026 Nutanix. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

---
apiVersion: v1
kind: Secret
metadata:
  name: ${CLUSTER_NAME}-flow-image-pull-secret
type: kubernetes.io/dockerconfigjson # The specific type K8s looks for
stringData:
  .dockerconfigjson: |
    {
      "auths": {
        "https://index.docker.io/v1/": {
          "auth": "${NUTANIX_FLOW_DOCKER_HUB_AUTH_BASICAUTH_BASE64}"
        }
      }
    }
