# Copyright 2025 Nutanix. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

---
apiVersion: v1
kind: Secret
metadata:
  name: ${CLUSTER_NAME}-pc-creds-for-konnector-agent
stringData:
  username: "${NUTANIX_USER}"
  password: "${NUTANIX_PASSWORD}"
