createPrismCentralSecret: false
pcSecretName: nutanix-csi-credentials

tolerations:
  - key: CriticalAddonsOnly
    operator: Exists
  - effect: NoExecute
    operator: Exists
    tolerationSeconds: 300
  - effect: NoSchedule
    key: node-role.kubernetes.io/master
    operator: Exists
  - effect: NoSchedule
    key: node-role.kubernetes.io/control-plane
    operator: Exists

# TODO Remove this once the Nutanix 3.0 CSI driver is GA.
supportedPCVersions: master,fraser-2024.1-stable-pc-0,fraser-2023.4-stable-pc-0,fraser-2024.1-stable-pc-0.1
