agent:
  name: {{ .AgentName }}
  image:
    privateRegistry: false
pc:
  port: {{ .PrismCentralPort }}
  insecure: {{ .PrismCentralInsecure }}
  endpoint: {{ .PrismCentralHost }}
k8sClusterName: {{ .ClusterName }}
k8sDistribution: NKP
createSecret: false
{{- if .CategoryMappings }}
categoryMappings: {{ .CategoryMappings }}
{{- end }}
{{- if and (ne .EnableKubeconfigUpload false) .ControlPlaneEndpoint }}
kubeconfigUpload:
  enabled: true
  controlPlaneEndpoint: {{ .ControlPlaneEndpoint }}
{{- end }}
