agent:
  name: {{ .AgentName }}
  image:
    privateRegistry: false
    repository: quay.io/karbon
    name: k8s-agent
    tag: "1.4.0-rc.1"
pc:
  port: {{ .PrismCentralPort }}
  insecure: {{ .PrismCentralInsecure }}
  endpoint: {{ .PrismCentralHost }}

k8sClusterName: {{ .ClusterName }}
k8sDistribution: NKP
createSecret: false
prismCredentialsSecretName: "{{ .PrismCredentialsSecretName }}"
{{- if .CategoryMappings }}
categoryMappings: {{ .CategoryMappings }}
{{- end }}
kubeconfigUpload:
  enabled: {{ .EnableKubeconfigUpload }}
{{- if .ControlPlaneEndpoint }}
  controlPlaneEndpoint: "{{ .ControlPlaneEndpoint }}"
{{- end }}
