agent:
  name: {{ .AgentName }}
  image:
    privateRegistry: false
    repository: quay.io/karbon
    name: k8s-agent
pc:
  port: {{ .PrismCentralPort }}
  insecure: {{ .PrismCentralInsecure }}
  endpoint: {{ .PrismCentralHost }}

prismCredentialsSecretName: dummy-secret
k8sClusterName: {{ .ClusterName }}
k8sDistribution: NKP
createSecret: false
{{- if .CategoryMappings }}
categoryMappings: {{ .CategoryMappings }}
{{- end }}
