# Copyright 2024 Nutanix. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

---
cni:
  chainingMode: portmap
  exclusive: false
hubble:
  enabled: false
ipam:
  mode: kubernetes
image:
  useDigest: false
operator:
  image:
    useDigest: false
certgen:
  image:
    useDigest: false
socketLB:
  hostNamespaceOnly: true
