# Copyright 2023 D2iQ, Inc. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

apiVersion: trust.cert-manager.io/v1alpha1
kind: Bundle
metadata:
  name: caren-bundle
spec:
  sources:
  - useDefaultCAs: true
  - secret:
      key: tls.crt
      name: mindthegap-tls
  target:
    configMap:
      key: ca-certificates.crt
    namespaceSelector:
      matchLabels:
        clusterctl.cluster.x-k8s.io: ""
