# Copyright 2023 Nutanix. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ template "chart.name" . }}-runtimehooks-tls
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "chart.labels" . | nindent 4 }}
spec:
  dnsNames:
    - {{ template "chart.name" . }}-runtimehooks.{{ .Release.Namespace }}.svc
    - {{ template "chart.name" . }}-runtimehooks.{{ .Release.Namespace }}.svc.cluster.local
  issuerRef:
    kind: {{ .Values.certificates.issuer.kind }}
    name: {{ template "chart.issuerName" . }}
  secretName: {{ template "chart.name" . }}-runtimehooks-tls
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ template "chart.name" . }}-admission-tls
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "chart.labels" . | nindent 4 }}
spec:
  dnsNames:
    - {{ template "chart.name" . }}-admission.{{ .Release.Namespace }}.svc
    - {{ template "chart.name" . }}-admission.{{ .Release.Namespace }}.svc.cluster.local
  issuerRef:
    kind: {{ .Values.certificates.issuer.kind }}
    name: {{ template "chart.issuerName" . }}
  secretName: {{ template "chart.name" . }}-admission-tls
