# Copyright 2023 Nutanix. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  labels:
{{ include "chart.labels" . | indent 4 }}
  name: {{ include "chart.name" . }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "chart.name" . }}-manager-role
subjects:
- kind: ServiceAccount
  name: {{ include "chart.name" . }}
  namespace: {{ .Release.Namespace }}
