# Copyright 2023 Nutanix. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

{{- if and .Values.deployDefaultClusterClasses (.Capabilities.APIVersions.Has "infrastructure.cluster.x-k8s.io/v1beta1/NutanixClusterTemplate") }}
{{ range $path, $_ :=  .Files.Glob  "clusterclasses/default/nutanix-*.yaml" }}
---
{{ $.Files.Get $path }}
{{ end }}
{{- end}}
