# Copyright 2023 Nutanix. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

{{- if .Values.certificates.issuer.selfSigned }}
apiVersion: cert-manager.io/v1
kind: {{ .Values.certificates.issuer.kind }}
metadata:
  name: {{ template "chart.issuerName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "chart.labels" . | nindent 4 }}
spec:
  selfSigned: {}
{{- end }}
