#!/usr/bin/env bash

GIT_REPO_ROOT="$(git rev-parse --show-toplevel)"
export GIT_REPO_ROOT

trap_add() {
  local -r sig="${2:?Signal required}"
  local -r hdls="$(trap -p "${sig}" | cut -f2 -d \')"
  # shellcheck disable=SC2064 # Quotes are required here to properly expand when adding the new trap.
  trap "${hdls}${hdls:+;}${1:?Handler required}" "${sig}"
}

function prepend_generated_by_header() {
  dst_file="$1"
  generated_by="$2"

  tmp_dir=$(mktemp -d)
  trap 'rm -rf $tmp_dir' RETURN

  generated_by_header_file="${tmp_dir}/header.txt"
  printf "#=================================================================\n\
#                 DO NOT EDIT THIS FILE\n\
#  IT HAS BEEN GENERATED BY %s\n\
#=================================================================\n\
" "$generated_by" >"$generated_by_header_file"

  tmp_dst_file="${tmp_dir}/dst.txt"
  cat "$generated_by_header_file" "$dst_file" >"$tmp_dst_file"
  mv "$tmp_dst_file" "$dst_file"
}
