//go:build !ignore_autogenerated

// Copyright 2024 Nutanix. All rights reserved.
// SPDX-License-Identifier: Apache-2.0

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"github.com/nutanix-cloud-native/cluster-api-runtime-extensions-nutanix/api/external/github.com/nutanix-cloud-native/cluster-api-provider-nutanix/api/v1beta1"
	"github.com/nutanix-cloud-native/cluster-api-runtime-extensions-nutanix/api/external/sigs.k8s.io/cluster-api-provider-aws/v2/api/v1beta2"
	"k8s.io/api/core/v1"
	storagev1 "k8s.io/api/storage/v1"
	"k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AESConfiguration) DeepCopyInto(out *AESConfiguration) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AESConfiguration.
func (in *AESConfiguration) DeepCopy() *AESConfiguration {
	if in == nil {
		return nil
	}
	out := new(AESConfiguration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AMILookup) DeepCopyInto(out *AMILookup) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AMILookup.
func (in *AMILookup) DeepCopy() *AMILookup {
	if in == nil {
		return nil
	}
	out := new(AMILookup)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AMISpec) DeepCopyInto(out *AMISpec) {
	*out = *in
	if in.Lookup != nil {
		in, out := &in.Lookup, &out.Lookup
		*out = new(AMILookup)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AMISpec.
func (in *AMISpec) DeepCopy() *AMISpec {
	if in == nil {
		return nil
	}
	out := new(AMISpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AWSAddons) DeepCopyInto(out *AWSAddons) {
	*out = *in
	in.GenericAddons.DeepCopyInto(&out.GenericAddons)
	if in.CSI != nil {
		in, out := &in.CSI, &out.CSI
		*out = new(AWSCSI)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AWSAddons.
func (in *AWSAddons) DeepCopy() *AWSAddons {
	if in == nil {
		return nil
	}
	out := new(AWSAddons)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AWSCSI) DeepCopyInto(out *AWSCSI) {
	*out = *in
	in.GenericCSI.DeepCopyInto(&out.GenericCSI)
	in.Providers.DeepCopyInto(&out.Providers)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AWSCSI.
func (in *AWSCSI) DeepCopy() *AWSCSI {
	if in == nil {
		return nil
	}
	out := new(AWSCSI)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AWSCSIProviders) DeepCopyInto(out *AWSCSIProviders) {
	*out = *in
	in.AWSEBSCSI.DeepCopyInto(&out.AWSEBSCSI)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AWSCSIProviders.
func (in *AWSCSIProviders) DeepCopy() *AWSCSIProviders {
	if in == nil {
		return nil
	}
	out := new(AWSCSIProviders)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AWSClusterConfig) DeepCopyInto(out *AWSClusterConfig) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AWSClusterConfig.
func (in *AWSClusterConfig) DeepCopy() *AWSClusterConfig {
	if in == nil {
		return nil
	}
	out := new(AWSClusterConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AWSClusterConfig) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AWSClusterConfigSpec) DeepCopyInto(out *AWSClusterConfigSpec) {
	*out = *in
	if in.AWS != nil {
		in, out := &in.AWS, &out.AWS
		*out = new(AWSSpec)
		(*in).DeepCopyInto(*out)
	}
	in.GenericClusterConfigResource.DeepCopyInto(&out.GenericClusterConfigResource)
	if in.Addons != nil {
		in, out := &in.Addons, &out.Addons
		*out = new(AWSAddons)
		(*in).DeepCopyInto(*out)
	}
	if in.ControlPlane != nil {
		in, out := &in.ControlPlane, &out.ControlPlane
		*out = new(AWSControlPlaneSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.ExtraAPIServerCertSANs != nil {
		in, out := &in.ExtraAPIServerCertSANs, &out.ExtraAPIServerCertSANs
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AWSClusterConfigSpec.
func (in *AWSClusterConfigSpec) DeepCopy() *AWSClusterConfigSpec {
	if in == nil {
		return nil
	}
	out := new(AWSClusterConfigSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AWSControlPlaneNodeSpec) DeepCopyInto(out *AWSControlPlaneNodeSpec) {
	*out = *in
	in.AWSGenericNodeSpec.DeepCopyInto(&out.AWSGenericNodeSpec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AWSControlPlaneNodeSpec.
func (in *AWSControlPlaneNodeSpec) DeepCopy() *AWSControlPlaneNodeSpec {
	if in == nil {
		return nil
	}
	out := new(AWSControlPlaneNodeSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AWSControlPlaneSpec) DeepCopyInto(out *AWSControlPlaneSpec) {
	*out = *in
	if in.AWS != nil {
		in, out := &in.AWS, &out.AWS
		*out = new(AWSControlPlaneNodeSpec)
		(*in).DeepCopyInto(*out)
	}
	in.GenericControlPlaneSpec.DeepCopyInto(&out.GenericControlPlaneSpec)
	in.GenericNodeSpec.DeepCopyInto(&out.GenericNodeSpec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AWSControlPlaneSpec.
func (in *AWSControlPlaneSpec) DeepCopy() *AWSControlPlaneSpec {
	if in == nil {
		return nil
	}
	out := new(AWSControlPlaneSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AWSGenericNodeSpec) DeepCopyInto(out *AWSGenericNodeSpec) {
	*out = *in
	if in.AMISpec != nil {
		in, out := &in.AMISpec, &out.AMISpec
		*out = new(AMISpec)
		(*in).DeepCopyInto(*out)
	}
	if in.AdditionalSecurityGroups != nil {
		in, out := &in.AdditionalSecurityGroups, &out.AdditionalSecurityGroups
		*out = make(AdditionalSecurityGroup, len(*in))
		copy(*out, *in)
	}
	if in.PlacementGroup != nil {
		in, out := &in.PlacementGroup, &out.PlacementGroup
		*out = new(PlacementGroup)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AWSGenericNodeSpec.
func (in *AWSGenericNodeSpec) DeepCopy() *AWSGenericNodeSpec {
	if in == nil {
		return nil
	}
	out := new(AWSGenericNodeSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AWSLoadBalancerSpec) DeepCopyInto(out *AWSLoadBalancerSpec) {
	*out = *in
	if in.Scheme != nil {
		in, out := &in.Scheme, &out.Scheme
		*out = new(v1beta2.ELBScheme)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AWSLoadBalancerSpec.
func (in *AWSLoadBalancerSpec) DeepCopy() *AWSLoadBalancerSpec {
	if in == nil {
		return nil
	}
	out := new(AWSLoadBalancerSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AWSNetwork) DeepCopyInto(out *AWSNetwork) {
	*out = *in
	if in.VPC != nil {
		in, out := &in.VPC, &out.VPC
		*out = new(VPC)
		**out = **in
	}
	if in.Subnets != nil {
		in, out := &in.Subnets, &out.Subnets
		*out = make(Subnets, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AWSNetwork.
func (in *AWSNetwork) DeepCopy() *AWSNetwork {
	if in == nil {
		return nil
	}
	out := new(AWSNetwork)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AWSSpec) DeepCopyInto(out *AWSSpec) {
	*out = *in
	if in.Region != nil {
		in, out := &in.Region, &out.Region
		*out = new(Region)
		**out = **in
	}
	if in.Network != nil {
		in, out := &in.Network, &out.Network
		*out = new(AWSNetwork)
		(*in).DeepCopyInto(*out)
	}
	if in.ControlPlaneLoadBalancer != nil {
		in, out := &in.ControlPlaneLoadBalancer, &out.ControlPlaneLoadBalancer
		*out = new(AWSLoadBalancerSpec)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AWSSpec.
func (in *AWSSpec) DeepCopy() *AWSSpec {
	if in == nil {
		return nil
	}
	out := new(AWSSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AWSWorkerNodeConfig) DeepCopyInto(out *AWSWorkerNodeConfig) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AWSWorkerNodeConfig.
func (in *AWSWorkerNodeConfig) DeepCopy() *AWSWorkerNodeConfig {
	if in == nil {
		return nil
	}
	out := new(AWSWorkerNodeConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AWSWorkerNodeConfig) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AWSWorkerNodeConfigSpec) DeepCopyInto(out *AWSWorkerNodeConfigSpec) {
	*out = *in
	if in.AWS != nil {
		in, out := &in.AWS, &out.AWS
		*out = new(AWSWorkerNodeSpec)
		(*in).DeepCopyInto(*out)
	}
	in.GenericNodeSpec.DeepCopyInto(&out.GenericNodeSpec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AWSWorkerNodeConfigSpec.
func (in *AWSWorkerNodeConfigSpec) DeepCopy() *AWSWorkerNodeConfigSpec {
	if in == nil {
		return nil
	}
	out := new(AWSWorkerNodeConfigSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AWSWorkerNodeSpec) DeepCopyInto(out *AWSWorkerNodeSpec) {
	*out = *in
	in.AWSGenericNodeSpec.DeepCopyInto(&out.AWSGenericNodeSpec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AWSWorkerNodeSpec.
func (in *AWSWorkerNodeSpec) DeepCopy() *AWSWorkerNodeSpec {
	if in == nil {
		return nil
	}
	out := new(AWSWorkerNodeSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in AdditionalSecurityGroup) DeepCopyInto(out *AdditionalSecurityGroup) {
	{
		in := &in
		*out = make(AdditionalSecurityGroup, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AdditionalSecurityGroup.
func (in AdditionalSecurityGroup) DeepCopy() AdditionalSecurityGroup {
	if in == nil {
		return nil
	}
	out := new(AdditionalSecurityGroup)
	in.DeepCopyInto(out)
	return *out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AddonConfig) DeepCopyInto(out *AddonConfig) {
	*out = *in
	if in.Values != nil {
		in, out := &in.Values, &out.Values
		*out = new(AddonValues)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AddonConfig.
func (in *AddonConfig) DeepCopy() *AddonConfig {
	if in == nil {
		return nil
	}
	out := new(AddonConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AddonValues) DeepCopyInto(out *AddonValues) {
	*out = *in
	if in.SourceRef != nil {
		in, out := &in.SourceRef, &out.SourceRef
		*out = new(ValuesReference)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AddonValues.
func (in *AddonValues) DeepCopy() *AddonValues {
	if in == nil {
		return nil
	}
	out := new(AddonValues)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AddressRange) DeepCopyInto(out *AddressRange) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AddressRange.
func (in *AddressRange) DeepCopy() *AddressRange {
	if in == nil {
		return nil
	}
	out := new(AddressRange)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AutoRenewCertificatesSpec) DeepCopyInto(out *AutoRenewCertificatesSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AutoRenewCertificatesSpec.
func (in *AutoRenewCertificatesSpec) DeepCopy() *AutoRenewCertificatesSpec {
	if in == nil {
		return nil
	}
	out := new(AutoRenewCertificatesSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CCM) DeepCopyInto(out *CCM) {
	*out = *in
	if in.Credentials != nil {
		in, out := &in.Credentials, &out.Credentials
		*out = new(CCMCredentials)
		**out = **in
	}
	if in.Strategy != nil {
		in, out := &in.Strategy, &out.Strategy
		*out = new(AddonStrategy)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CCM.
func (in *CCM) DeepCopy() *CCM {
	if in == nil {
		return nil
	}
	out := new(CCM)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CCMCredentials) DeepCopyInto(out *CCMCredentials) {
	*out = *in
	out.SecretRef = in.SecretRef
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CCMCredentials.
func (in *CCMCredentials) DeepCopy() *CCMCredentials {
	if in == nil {
		return nil
	}
	out := new(CCMCredentials)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CNI) DeepCopyInto(out *CNI) {
	*out = *in
	if in.Strategy != nil {
		in, out := &in.Strategy, &out.Strategy
		*out = new(AddonStrategy)
		**out = **in
	}
	in.AddonConfig.DeepCopyInto(&out.AddonConfig)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CNI.
func (in *CNI) DeepCopy() *CNI {
	if in == nil {
		return nil
	}
	out := new(CNI)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CSICredentials) DeepCopyInto(out *CSICredentials) {
	*out = *in
	out.SecretRef = in.SecretRef
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CSICredentials.
func (in *CSICredentials) DeepCopy() *CSICredentials {
	if in == nil {
		return nil
	}
	out := new(CSICredentials)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CSIProvider) DeepCopyInto(out *CSIProvider) {
	*out = *in
	if in.StorageClassConfigs != nil {
		in, out := &in.StorageClassConfigs, &out.StorageClassConfigs
		*out = make(map[string]StorageClassConfig, len(*in))
		for key, val := range *in {
			(*out)[key] = *val.DeepCopy()
		}
	}
	if in.Strategy != nil {
		in, out := &in.Strategy, &out.Strategy
		*out = new(AddonStrategy)
		**out = **in
	}
	if in.Credentials != nil {
		in, out := &in.Credentials, &out.Credentials
		*out = new(CSICredentials)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CSIProvider.
func (in *CSIProvider) DeepCopy() *CSIProvider {
	if in == nil {
		return nil
	}
	out := new(CSIProvider)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterAutoscaler) DeepCopyInto(out *ClusterAutoscaler) {
	*out = *in
	if in.Strategy != nil {
		in, out := &in.Strategy, &out.Strategy
		*out = new(AddonStrategy)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterAutoscaler.
func (in *ClusterAutoscaler) DeepCopy() *ClusterAutoscaler {
	if in == nil {
		return nil
	}
	out := new(ClusterAutoscaler)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ControlPlaneEndpointSpec) DeepCopyInto(out *ControlPlaneEndpointSpec) {
	*out = *in
	if in.VirtualIPSpec != nil {
		in, out := &in.VirtualIPSpec, &out.VirtualIPSpec
		*out = new(ControlPlaneVirtualIPSpec)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ControlPlaneEndpointSpec.
func (in *ControlPlaneEndpointSpec) DeepCopy() *ControlPlaneEndpointSpec {
	if in == nil {
		return nil
	}
	out := new(ControlPlaneEndpointSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ControlPlaneVirtualIPConfiguration) DeepCopyInto(out *ControlPlaneVirtualIPConfiguration) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ControlPlaneVirtualIPConfiguration.
func (in *ControlPlaneVirtualIPConfiguration) DeepCopy() *ControlPlaneVirtualIPConfiguration {
	if in == nil {
		return nil
	}
	out := new(ControlPlaneVirtualIPConfiguration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ControlPlaneVirtualIPSpec) DeepCopyInto(out *ControlPlaneVirtualIPSpec) {
	*out = *in
	if in.Configuration != nil {
		in, out := &in.Configuration, &out.Configuration
		*out = new(ControlPlaneVirtualIPConfiguration)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ControlPlaneVirtualIPSpec.
func (in *ControlPlaneVirtualIPSpec) DeepCopy() *ControlPlaneVirtualIPSpec {
	if in == nil {
		return nil
	}
	out := new(ControlPlaneVirtualIPSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CoreDNS) DeepCopyInto(out *CoreDNS) {
	*out = *in
	if in.Image != nil {
		in, out := &in.Image, &out.Image
		*out = new(Image)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CoreDNS.
func (in *CoreDNS) DeepCopy() *CoreDNS {
	if in == nil {
		return nil
	}
	out := new(CoreDNS)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DNS) DeepCopyInto(out *DNS) {
	*out = *in
	if in.CoreDNS != nil {
		in, out := &in.CoreDNS, &out.CoreDNS
		*out = new(CoreDNS)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DNS.
func (in *DNS) DeepCopy() *DNS {
	if in == nil {
		return nil
	}
	out := new(DNS)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DefaultStorage) DeepCopyInto(out *DefaultStorage) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DefaultStorage.
func (in *DefaultStorage) DeepCopy() *DefaultStorage {
	if in == nil {
		return nil
	}
	out := new(DefaultStorage)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DockerAddons) DeepCopyInto(out *DockerAddons) {
	*out = *in
	in.GenericAddons.DeepCopyInto(&out.GenericAddons)
	if in.CSI != nil {
		in, out := &in.CSI, &out.CSI
		*out = new(DockerCSI)
		(*in).DeepCopyInto(*out)
	}
	if in.COSI != nil {
		in, out := &in.COSI, &out.COSI
		*out = new(DockerCOSI)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DockerAddons.
func (in *DockerAddons) DeepCopy() *DockerAddons {
	if in == nil {
		return nil
	}
	out := new(DockerAddons)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DockerCOSI) DeepCopyInto(out *DockerCOSI) {
	*out = *in
	in.GenericCOSI.DeepCopyInto(&out.GenericCOSI)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DockerCOSI.
func (in *DockerCOSI) DeepCopy() *DockerCOSI {
	if in == nil {
		return nil
	}
	out := new(DockerCOSI)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DockerCSI) DeepCopyInto(out *DockerCSI) {
	*out = *in
	in.GenericCSI.DeepCopyInto(&out.GenericCSI)
	in.Providers.DeepCopyInto(&out.Providers)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DockerCSI.
func (in *DockerCSI) DeepCopy() *DockerCSI {
	if in == nil {
		return nil
	}
	out := new(DockerCSI)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DockerCSIProviders) DeepCopyInto(out *DockerCSIProviders) {
	*out = *in
	in.LocalPathCSI.DeepCopyInto(&out.LocalPathCSI)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DockerCSIProviders.
func (in *DockerCSIProviders) DeepCopy() *DockerCSIProviders {
	if in == nil {
		return nil
	}
	out := new(DockerCSIProviders)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DockerClusterConfig) DeepCopyInto(out *DockerClusterConfig) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DockerClusterConfig.
func (in *DockerClusterConfig) DeepCopy() *DockerClusterConfig {
	if in == nil {
		return nil
	}
	out := new(DockerClusterConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DockerClusterConfig) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DockerClusterConfigSpec) DeepCopyInto(out *DockerClusterConfigSpec) {
	*out = *in
	if in.Docker != nil {
		in, out := &in.Docker, &out.Docker
		*out = new(DockerSpec)
		**out = **in
	}
	in.GenericClusterConfigResource.DeepCopyInto(&out.GenericClusterConfigResource)
	if in.Addons != nil {
		in, out := &in.Addons, &out.Addons
		*out = new(DockerAddons)
		(*in).DeepCopyInto(*out)
	}
	if in.ControlPlane != nil {
		in, out := &in.ControlPlane, &out.ControlPlane
		*out = new(DockerControlPlaneSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.ExtraAPIServerCertSANs != nil {
		in, out := &in.ExtraAPIServerCertSANs, &out.ExtraAPIServerCertSANs
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DockerClusterConfigSpec.
func (in *DockerClusterConfigSpec) DeepCopy() *DockerClusterConfigSpec {
	if in == nil {
		return nil
	}
	out := new(DockerClusterConfigSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DockerControlPlaneSpec) DeepCopyInto(out *DockerControlPlaneSpec) {
	*out = *in
	if in.Docker != nil {
		in, out := &in.Docker, &out.Docker
		*out = new(DockerNodeSpec)
		(*in).DeepCopyInto(*out)
	}
	in.GenericControlPlaneSpec.DeepCopyInto(&out.GenericControlPlaneSpec)
	in.GenericNodeSpec.DeepCopyInto(&out.GenericNodeSpec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DockerControlPlaneSpec.
func (in *DockerControlPlaneSpec) DeepCopy() *DockerControlPlaneSpec {
	if in == nil {
		return nil
	}
	out := new(DockerControlPlaneSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DockerNodeSpec) DeepCopyInto(out *DockerNodeSpec) {
	*out = *in
	if in.CustomImage != nil {
		in, out := &in.CustomImage, &out.CustomImage
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DockerNodeSpec.
func (in *DockerNodeSpec) DeepCopy() *DockerNodeSpec {
	if in == nil {
		return nil
	}
	out := new(DockerNodeSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DockerSpec) DeepCopyInto(out *DockerSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DockerSpec.
func (in *DockerSpec) DeepCopy() *DockerSpec {
	if in == nil {
		return nil
	}
	out := new(DockerSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DockerWorkerNodeConfig) DeepCopyInto(out *DockerWorkerNodeConfig) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DockerWorkerNodeConfig.
func (in *DockerWorkerNodeConfig) DeepCopy() *DockerWorkerNodeConfig {
	if in == nil {
		return nil
	}
	out := new(DockerWorkerNodeConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DockerWorkerNodeConfig) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DockerWorkerNodeConfigSpec) DeepCopyInto(out *DockerWorkerNodeConfigSpec) {
	*out = *in
	if in.Docker != nil {
		in, out := &in.Docker, &out.Docker
		*out = new(DockerNodeSpec)
		(*in).DeepCopyInto(*out)
	}
	in.GenericNodeSpec.DeepCopyInto(&out.GenericNodeSpec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DockerWorkerNodeConfigSpec.
func (in *DockerWorkerNodeConfigSpec) DeepCopy() *DockerWorkerNodeConfigSpec {
	if in == nil {
		return nil
	}
	out := new(DockerWorkerNodeConfigSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EKSClusterConfig) DeepCopyInto(out *EKSClusterConfig) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EKSClusterConfig.
func (in *EKSClusterConfig) DeepCopy() *EKSClusterConfig {
	if in == nil {
		return nil
	}
	out := new(EKSClusterConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *EKSClusterConfig) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EKSClusterConfigSpec) DeepCopyInto(out *EKSClusterConfigSpec) {
	*out = *in
	if in.EKS != nil {
		in, out := &in.EKS, &out.EKS
		*out = new(EKSSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.Addons != nil {
		in, out := &in.Addons, &out.Addons
		*out = new(AWSAddons)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EKSClusterConfigSpec.
func (in *EKSClusterConfigSpec) DeepCopy() *EKSClusterConfigSpec {
	if in == nil {
		return nil
	}
	out := new(EKSClusterConfigSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EKSGenericNodeSpec) DeepCopyInto(out *EKSGenericNodeSpec) {
	*out = *in
	if in.Taints != nil {
		in, out := &in.Taints, &out.Taints
		*out = make([]Taint, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EKSGenericNodeSpec.
func (in *EKSGenericNodeSpec) DeepCopy() *EKSGenericNodeSpec {
	if in == nil {
		return nil
	}
	out := new(EKSGenericNodeSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EKSSpec) DeepCopyInto(out *EKSSpec) {
	*out = *in
	if in.Region != nil {
		in, out := &in.Region, &out.Region
		*out = new(Region)
		**out = **in
	}
	if in.Network != nil {
		in, out := &in.Network, &out.Network
		*out = new(AWSNetwork)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EKSSpec.
func (in *EKSSpec) DeepCopy() *EKSSpec {
	if in == nil {
		return nil
	}
	out := new(EKSSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EKSWorkerNodeConfig) DeepCopyInto(out *EKSWorkerNodeConfig) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EKSWorkerNodeConfig.
func (in *EKSWorkerNodeConfig) DeepCopy() *EKSWorkerNodeConfig {
	if in == nil {
		return nil
	}
	out := new(EKSWorkerNodeConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *EKSWorkerNodeConfig) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EKSWorkerNodeConfigSpec) DeepCopyInto(out *EKSWorkerNodeConfigSpec) {
	*out = *in
	if in.EKS != nil {
		in, out := &in.EKS, &out.EKS
		*out = new(EKSWorkerNodeSpec)
		(*in).DeepCopyInto(*out)
	}
	in.EKSGenericNodeSpec.DeepCopyInto(&out.EKSGenericNodeSpec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EKSWorkerNodeConfigSpec.
func (in *EKSWorkerNodeConfigSpec) DeepCopy() *EKSWorkerNodeConfigSpec {
	if in == nil {
		return nil
	}
	out := new(EKSWorkerNodeConfigSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EKSWorkerNodeSpec) DeepCopyInto(out *EKSWorkerNodeSpec) {
	*out = *in
	in.AWSWorkerNodeSpec.DeepCopyInto(&out.AWSWorkerNodeSpec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EKSWorkerNodeSpec.
func (in *EKSWorkerNodeSpec) DeepCopy() *EKSWorkerNodeSpec {
	if in == nil {
		return nil
	}
	out := new(EKSWorkerNodeSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EncryptionAtRest) DeepCopyInto(out *EncryptionAtRest) {
	*out = *in
	if in.Providers != nil {
		in, out := &in.Providers, &out.Providers
		*out = make([]EncryptionProviders, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EncryptionAtRest.
func (in *EncryptionAtRest) DeepCopy() *EncryptionAtRest {
	if in == nil {
		return nil
	}
	out := new(EncryptionAtRest)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EncryptionProviders) DeepCopyInto(out *EncryptionProviders) {
	*out = *in
	if in.AESCBC != nil {
		in, out := &in.AESCBC, &out.AESCBC
		*out = new(AESConfiguration)
		**out = **in
	}
	if in.Secretbox != nil {
		in, out := &in.Secretbox, &out.Secretbox
		*out = new(SecretboxConfiguration)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EncryptionProviders.
func (in *EncryptionProviders) DeepCopy() *EncryptionProviders {
	if in == nil {
		return nil
	}
	out := new(EncryptionProviders)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Etcd) DeepCopyInto(out *Etcd) {
	*out = *in
	if in.Image != nil {
		in, out := &in.Image, &out.Image
		*out = new(Image)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Etcd.
func (in *Etcd) DeepCopy() *Etcd {
	if in == nil {
		return nil
	}
	out := new(Etcd)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GenericAddons) DeepCopyInto(out *GenericAddons) {
	*out = *in
	if in.CNI != nil {
		in, out := &in.CNI, &out.CNI
		*out = new(CNI)
		(*in).DeepCopyInto(*out)
	}
	if in.NFD != nil {
		in, out := &in.NFD, &out.NFD
		*out = new(NFD)
		(*in).DeepCopyInto(*out)
	}
	if in.ClusterAutoscaler != nil {
		in, out := &in.ClusterAutoscaler, &out.ClusterAutoscaler
		*out = new(ClusterAutoscaler)
		(*in).DeepCopyInto(*out)
	}
	if in.CCM != nil {
		in, out := &in.CCM, &out.CCM
		*out = new(CCM)
		(*in).DeepCopyInto(*out)
	}
	if in.ServiceLoadBalancer != nil {
		in, out := &in.ServiceLoadBalancer, &out.ServiceLoadBalancer
		*out = new(ServiceLoadBalancer)
		(*in).DeepCopyInto(*out)
	}
	if in.Registry != nil {
		in, out := &in.Registry, &out.Registry
		*out = new(RegistryAddon)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GenericAddons.
func (in *GenericAddons) DeepCopy() *GenericAddons {
	if in == nil {
		return nil
	}
	out := new(GenericAddons)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GenericCOSI) DeepCopyInto(out *GenericCOSI) {
	*out = *in
	if in.Strategy != nil {
		in, out := &in.Strategy, &out.Strategy
		*out = new(AddonStrategy)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GenericCOSI.
func (in *GenericCOSI) DeepCopy() *GenericCOSI {
	if in == nil {
		return nil
	}
	out := new(GenericCOSI)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GenericCSI) DeepCopyInto(out *GenericCSI) {
	*out = *in
	out.DefaultStorage = in.DefaultStorage
	if in.SnapshotController != nil {
		in, out := &in.SnapshotController, &out.SnapshotController
		*out = new(SnapshotController)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GenericCSI.
func (in *GenericCSI) DeepCopy() *GenericCSI {
	if in == nil {
		return nil
	}
	out := new(GenericCSI)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GenericClusterConfig) DeepCopyInto(out *GenericClusterConfig) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	if in.ExtraAPIServerCertSANs != nil {
		in, out := &in.ExtraAPIServerCertSANs, &out.ExtraAPIServerCertSANs
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GenericClusterConfig.
func (in *GenericClusterConfig) DeepCopy() *GenericClusterConfig {
	if in == nil {
		return nil
	}
	out := new(GenericClusterConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *GenericClusterConfig) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GenericClusterConfigResource) DeepCopyInto(out *GenericClusterConfigResource) {
	*out = *in
	if in.KubernetesImageRepository != nil {
		in, out := &in.KubernetesImageRepository, &out.KubernetesImageRepository
		*out = new(string)
		**out = **in
	}
	if in.Etcd != nil {
		in, out := &in.Etcd, &out.Etcd
		*out = new(Etcd)
		(*in).DeepCopyInto(*out)
	}
	if in.Proxy != nil {
		in, out := &in.Proxy, &out.Proxy
		*out = new(HTTPProxy)
		(*in).DeepCopyInto(*out)
	}
	if in.ImageRegistries != nil {
		in, out := &in.ImageRegistries, &out.ImageRegistries
		*out = make([]ImageRegistry, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.GlobalImageRegistryMirror != nil {
		in, out := &in.GlobalImageRegistryMirror, &out.GlobalImageRegistryMirror
		*out = new(GlobalImageRegistryMirror)
		(*in).DeepCopyInto(*out)
	}
	if in.Users != nil {
		in, out := &in.Users, &out.Users
		*out = make([]User, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.EncryptionAtRest != nil {
		in, out := &in.EncryptionAtRest, &out.EncryptionAtRest
		*out = new(EncryptionAtRest)
		(*in).DeepCopyInto(*out)
	}
	if in.DNS != nil {
		in, out := &in.DNS, &out.DNS
		*out = new(DNS)
		(*in).DeepCopyInto(*out)
	}
	if in.KubeProxy != nil {
		in, out := &in.KubeProxy, &out.KubeProxy
		*out = new(KubeProxy)
		**out = **in
	}
	if in.NTP != nil {
		in, out := &in.NTP, &out.NTP
		*out = new(NTP)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GenericClusterConfigResource.
func (in *GenericClusterConfigResource) DeepCopy() *GenericClusterConfigResource {
	if in == nil {
		return nil
	}
	out := new(GenericClusterConfigResource)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GenericClusterConfigSpec) DeepCopyInto(out *GenericClusterConfigSpec) {
	*out = *in
	in.GenericClusterConfigResource.DeepCopyInto(&out.GenericClusterConfigResource)
	if in.Addons != nil {
		in, out := &in.Addons, &out.Addons
		*out = new(GenericAddons)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GenericClusterConfigSpec.
func (in *GenericClusterConfigSpec) DeepCopy() *GenericClusterConfigSpec {
	if in == nil {
		return nil
	}
	out := new(GenericClusterConfigSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GenericControlPlaneSpec) DeepCopyInto(out *GenericControlPlaneSpec) {
	*out = *in
	if in.AutoRenewCertificates != nil {
		in, out := &in.AutoRenewCertificates, &out.AutoRenewCertificates
		*out = new(AutoRenewCertificatesSpec)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GenericControlPlaneSpec.
func (in *GenericControlPlaneSpec) DeepCopy() *GenericControlPlaneSpec {
	if in == nil {
		return nil
	}
	out := new(GenericControlPlaneSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GenericNodeSpec) DeepCopyInto(out *GenericNodeSpec) {
	*out = *in
	if in.Taints != nil {
		in, out := &in.Taints, &out.Taints
		*out = make([]Taint, len(*in))
		copy(*out, *in)
	}
	if in.NodeRegistration != nil {
		in, out := &in.NodeRegistration, &out.NodeRegistration
		*out = new(NodeRegistrationOptions)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GenericNodeSpec.
func (in *GenericNodeSpec) DeepCopy() *GenericNodeSpec {
	if in == nil {
		return nil
	}
	out := new(GenericNodeSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GlobalImageRegistryMirror) DeepCopyInto(out *GlobalImageRegistryMirror) {
	*out = *in
	if in.Credentials != nil {
		in, out := &in.Credentials, &out.Credentials
		*out = new(RegistryCredentials)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GlobalImageRegistryMirror.
func (in *GlobalImageRegistryMirror) DeepCopy() *GlobalImageRegistryMirror {
	if in == nil {
		return nil
	}
	out := new(GlobalImageRegistryMirror)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HTTPProxy) DeepCopyInto(out *HTTPProxy) {
	*out = *in
	if in.AdditionalNo != nil {
		in, out := &in.AdditionalNo, &out.AdditionalNo
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HTTPProxy.
func (in *HTTPProxy) DeepCopy() *HTTPProxy {
	if in == nil {
		return nil
	}
	out := new(HTTPProxy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Image) DeepCopyInto(out *Image) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Image.
func (in *Image) DeepCopy() *Image {
	if in == nil {
		return nil
	}
	out := new(Image)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ImageRegistry) DeepCopyInto(out *ImageRegistry) {
	*out = *in
	if in.Credentials != nil {
		in, out := &in.Credentials, &out.Credentials
		*out = new(RegistryCredentials)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ImageRegistry.
func (in *ImageRegistry) DeepCopy() *ImageRegistry {
	if in == nil {
		return nil
	}
	out := new(ImageRegistry)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KubeProxy) DeepCopyInto(out *KubeProxy) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KubeProxy.
func (in *KubeProxy) DeepCopy() *KubeProxy {
	if in == nil {
		return nil
	}
	out := new(KubeProxy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LocalObjectReference) DeepCopyInto(out *LocalObjectReference) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LocalObjectReference.
func (in *LocalObjectReference) DeepCopy() *LocalObjectReference {
	if in == nil {
		return nil
	}
	out := new(LocalObjectReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NFD) DeepCopyInto(out *NFD) {
	*out = *in
	if in.Strategy != nil {
		in, out := &in.Strategy, &out.Strategy
		*out = new(AddonStrategy)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NFD.
func (in *NFD) DeepCopy() *NFD {
	if in == nil {
		return nil
	}
	out := new(NFD)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NTP) DeepCopyInto(out *NTP) {
	*out = *in
	if in.Servers != nil {
		in, out := &in.Servers, &out.Servers
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NTP.
func (in *NTP) DeepCopy() *NTP {
	if in == nil {
		return nil
	}
	out := new(NTP)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodeRegistrationOptions) DeepCopyInto(out *NodeRegistrationOptions) {
	*out = *in
	if in.IgnorePreflightErrors != nil {
		in, out := &in.IgnorePreflightErrors, &out.IgnorePreflightErrors
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodeRegistrationOptions.
func (in *NodeRegistrationOptions) DeepCopy() *NodeRegistrationOptions {
	if in == nil {
		return nil
	}
	out := new(NodeRegistrationOptions)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NutanixAddons) DeepCopyInto(out *NutanixAddons) {
	*out = *in
	in.GenericAddons.DeepCopyInto(&out.GenericAddons)
	if in.CSI != nil {
		in, out := &in.CSI, &out.CSI
		*out = new(NutanixCSI)
		(*in).DeepCopyInto(*out)
	}
	if in.COSI != nil {
		in, out := &in.COSI, &out.COSI
		*out = new(NutanixCOSI)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NutanixAddons.
func (in *NutanixAddons) DeepCopy() *NutanixAddons {
	if in == nil {
		return nil
	}
	out := new(NutanixAddons)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NutanixCOSI) DeepCopyInto(out *NutanixCOSI) {
	*out = *in
	in.GenericCOSI.DeepCopyInto(&out.GenericCOSI)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NutanixCOSI.
func (in *NutanixCOSI) DeepCopy() *NutanixCOSI {
	if in == nil {
		return nil
	}
	out := new(NutanixCOSI)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NutanixCSI) DeepCopyInto(out *NutanixCSI) {
	*out = *in
	in.GenericCSI.DeepCopyInto(&out.GenericCSI)
	in.Providers.DeepCopyInto(&out.Providers)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NutanixCSI.
func (in *NutanixCSI) DeepCopy() *NutanixCSI {
	if in == nil {
		return nil
	}
	out := new(NutanixCSI)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NutanixCSIProviders) DeepCopyInto(out *NutanixCSIProviders) {
	*out = *in
	in.NutanixCSI.DeepCopyInto(&out.NutanixCSI)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NutanixCSIProviders.
func (in *NutanixCSIProviders) DeepCopy() *NutanixCSIProviders {
	if in == nil {
		return nil
	}
	out := new(NutanixCSIProviders)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NutanixClusterConfig) DeepCopyInto(out *NutanixClusterConfig) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NutanixClusterConfig.
func (in *NutanixClusterConfig) DeepCopy() *NutanixClusterConfig {
	if in == nil {
		return nil
	}
	out := new(NutanixClusterConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *NutanixClusterConfig) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NutanixClusterConfigSpec) DeepCopyInto(out *NutanixClusterConfigSpec) {
	*out = *in
	if in.Nutanix != nil {
		in, out := &in.Nutanix, &out.Nutanix
		*out = new(NutanixSpec)
		(*in).DeepCopyInto(*out)
	}
	in.GenericClusterConfigResource.DeepCopyInto(&out.GenericClusterConfigResource)
	if in.Addons != nil {
		in, out := &in.Addons, &out.Addons
		*out = new(NutanixAddons)
		(*in).DeepCopyInto(*out)
	}
	if in.ControlPlane != nil {
		in, out := &in.ControlPlane, &out.ControlPlane
		*out = new(NutanixControlPlaneSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.ExtraAPIServerCertSANs != nil {
		in, out := &in.ExtraAPIServerCertSANs, &out.ExtraAPIServerCertSANs
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NutanixClusterConfigSpec.
func (in *NutanixClusterConfigSpec) DeepCopy() *NutanixClusterConfigSpec {
	if in == nil {
		return nil
	}
	out := new(NutanixClusterConfigSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NutanixControlPlaneNodeSpec) DeepCopyInto(out *NutanixControlPlaneNodeSpec) {
	*out = *in
	in.MachineDetails.DeepCopyInto(&out.MachineDetails)
	if in.FailureDomains != nil {
		in, out := &in.FailureDomains, &out.FailureDomains
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NutanixControlPlaneNodeSpec.
func (in *NutanixControlPlaneNodeSpec) DeepCopy() *NutanixControlPlaneNodeSpec {
	if in == nil {
		return nil
	}
	out := new(NutanixControlPlaneNodeSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NutanixControlPlaneSpec) DeepCopyInto(out *NutanixControlPlaneSpec) {
	*out = *in
	if in.Nutanix != nil {
		in, out := &in.Nutanix, &out.Nutanix
		*out = new(NutanixControlPlaneNodeSpec)
		(*in).DeepCopyInto(*out)
	}
	in.GenericControlPlaneSpec.DeepCopyInto(&out.GenericControlPlaneSpec)
	in.GenericNodeSpec.DeepCopyInto(&out.GenericNodeSpec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NutanixControlPlaneSpec.
func (in *NutanixControlPlaneSpec) DeepCopy() *NutanixControlPlaneSpec {
	if in == nil {
		return nil
	}
	out := new(NutanixControlPlaneSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NutanixMachineDetails) DeepCopyInto(out *NutanixMachineDetails) {
	*out = *in
	out.MemorySize = in.MemorySize.DeepCopy()
	if in.Image != nil {
		in, out := &in.Image, &out.Image
		*out = new(v1beta1.NutanixResourceIdentifier)
		(*in).DeepCopyInto(*out)
	}
	if in.ImageLookup != nil {
		in, out := &in.ImageLookup, &out.ImageLookup
		*out = new(v1beta1.NutanixImageLookup)
		(*in).DeepCopyInto(*out)
	}
	if in.Cluster != nil {
		in, out := &in.Cluster, &out.Cluster
		*out = new(v1beta1.NutanixResourceIdentifier)
		(*in).DeepCopyInto(*out)
	}
	if in.Subnets != nil {
		in, out := &in.Subnets, &out.Subnets
		*out = make([]v1beta1.NutanixResourceIdentifier, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.AdditionalCategories != nil {
		in, out := &in.AdditionalCategories, &out.AdditionalCategories
		*out = make([]v1beta1.NutanixCategoryIdentifier, len(*in))
		copy(*out, *in)
	}
	out.SystemDiskSize = in.SystemDiskSize.DeepCopy()
	if in.Project != nil {
		in, out := &in.Project, &out.Project
		*out = new(v1beta1.NutanixResourceIdentifier)
		(*in).DeepCopyInto(*out)
	}
	if in.GPUs != nil {
		in, out := &in.GPUs, &out.GPUs
		*out = make([]v1beta1.NutanixGPU, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NutanixMachineDetails.
func (in *NutanixMachineDetails) DeepCopy() *NutanixMachineDetails {
	if in == nil {
		return nil
	}
	out := new(NutanixMachineDetails)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NutanixPrismCentralEndpointCredentials) DeepCopyInto(out *NutanixPrismCentralEndpointCredentials) {
	*out = *in
	out.SecretRef = in.SecretRef
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NutanixPrismCentralEndpointCredentials.
func (in *NutanixPrismCentralEndpointCredentials) DeepCopy() *NutanixPrismCentralEndpointCredentials {
	if in == nil {
		return nil
	}
	out := new(NutanixPrismCentralEndpointCredentials)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NutanixPrismCentralEndpointSpec) DeepCopyInto(out *NutanixPrismCentralEndpointSpec) {
	*out = *in
	out.Credentials = in.Credentials
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NutanixPrismCentralEndpointSpec.
func (in *NutanixPrismCentralEndpointSpec) DeepCopy() *NutanixPrismCentralEndpointSpec {
	if in == nil {
		return nil
	}
	out := new(NutanixPrismCentralEndpointSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NutanixSpec) DeepCopyInto(out *NutanixSpec) {
	*out = *in
	in.ControlPlaneEndpoint.DeepCopyInto(&out.ControlPlaneEndpoint)
	out.PrismCentralEndpoint = in.PrismCentralEndpoint
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NutanixSpec.
func (in *NutanixSpec) DeepCopy() *NutanixSpec {
	if in == nil {
		return nil
	}
	out := new(NutanixSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NutanixWorkerNodeConfig) DeepCopyInto(out *NutanixWorkerNodeConfig) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NutanixWorkerNodeConfig.
func (in *NutanixWorkerNodeConfig) DeepCopy() *NutanixWorkerNodeConfig {
	if in == nil {
		return nil
	}
	out := new(NutanixWorkerNodeConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *NutanixWorkerNodeConfig) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NutanixWorkerNodeConfigSpec) DeepCopyInto(out *NutanixWorkerNodeConfigSpec) {
	*out = *in
	if in.Nutanix != nil {
		in, out := &in.Nutanix, &out.Nutanix
		*out = new(NutanixWorkerNodeSpec)
		(*in).DeepCopyInto(*out)
	}
	in.GenericNodeSpec.DeepCopyInto(&out.GenericNodeSpec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NutanixWorkerNodeConfigSpec.
func (in *NutanixWorkerNodeConfigSpec) DeepCopy() *NutanixWorkerNodeConfigSpec {
	if in == nil {
		return nil
	}
	out := new(NutanixWorkerNodeConfigSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NutanixWorkerNodeSpec) DeepCopyInto(out *NutanixWorkerNodeSpec) {
	*out = *in
	in.MachineDetails.DeepCopyInto(&out.MachineDetails)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NutanixWorkerNodeSpec.
func (in *NutanixWorkerNodeSpec) DeepCopy() *NutanixWorkerNodeSpec {
	if in == nil {
		return nil
	}
	out := new(NutanixWorkerNodeSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ObjectMeta) DeepCopyInto(out *ObjectMeta) {
	*out = *in
	if in.Labels != nil {
		in, out := &in.Labels, &out.Labels
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Annotations != nil {
		in, out := &in.Annotations, &out.Annotations
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ObjectMeta.
func (in *ObjectMeta) DeepCopy() *ObjectMeta {
	if in == nil {
		return nil
	}
	out := new(ObjectMeta)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PlacementGroup) DeepCopyInto(out *PlacementGroup) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PlacementGroup.
func (in *PlacementGroup) DeepCopy() *PlacementGroup {
	if in == nil {
		return nil
	}
	out := new(PlacementGroup)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RegistryAddon) DeepCopyInto(out *RegistryAddon) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RegistryAddon.
func (in *RegistryAddon) DeepCopy() *RegistryAddon {
	if in == nil {
		return nil
	}
	out := new(RegistryAddon)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RegistryCredentials) DeepCopyInto(out *RegistryCredentials) {
	*out = *in
	if in.SecretRef != nil {
		in, out := &in.SecretRef, &out.SecretRef
		*out = new(LocalObjectReference)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RegistryCredentials.
func (in *RegistryCredentials) DeepCopy() *RegistryCredentials {
	if in == nil {
		return nil
	}
	out := new(RegistryCredentials)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SecretboxConfiguration) DeepCopyInto(out *SecretboxConfiguration) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SecretboxConfiguration.
func (in *SecretboxConfiguration) DeepCopy() *SecretboxConfiguration {
	if in == nil {
		return nil
	}
	out := new(SecretboxConfiguration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SecurityGroup) DeepCopyInto(out *SecurityGroup) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SecurityGroup.
func (in *SecurityGroup) DeepCopy() *SecurityGroup {
	if in == nil {
		return nil
	}
	out := new(SecurityGroup)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ServiceLoadBalancer) DeepCopyInto(out *ServiceLoadBalancer) {
	*out = *in
	if in.Configuration != nil {
		in, out := &in.Configuration, &out.Configuration
		*out = new(ServiceLoadBalancerConfiguration)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ServiceLoadBalancer.
func (in *ServiceLoadBalancer) DeepCopy() *ServiceLoadBalancer {
	if in == nil {
		return nil
	}
	out := new(ServiceLoadBalancer)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ServiceLoadBalancerConfiguration) DeepCopyInto(out *ServiceLoadBalancerConfiguration) {
	*out = *in
	if in.AddressRanges != nil {
		in, out := &in.AddressRanges, &out.AddressRanges
		*out = make([]AddressRange, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ServiceLoadBalancerConfiguration.
func (in *ServiceLoadBalancerConfiguration) DeepCopy() *ServiceLoadBalancerConfiguration {
	if in == nil {
		return nil
	}
	out := new(ServiceLoadBalancerConfiguration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SnapshotController) DeepCopyInto(out *SnapshotController) {
	*out = *in
	if in.Strategy != nil {
		in, out := &in.Strategy, &out.Strategy
		*out = new(AddonStrategy)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SnapshotController.
func (in *SnapshotController) DeepCopy() *SnapshotController {
	if in == nil {
		return nil
	}
	out := new(SnapshotController)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StorageClassConfig) DeepCopyInto(out *StorageClassConfig) {
	*out = *in
	if in.Parameters != nil {
		in, out := &in.Parameters, &out.Parameters
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.ReclaimPolicy != nil {
		in, out := &in.ReclaimPolicy, &out.ReclaimPolicy
		*out = new(v1.PersistentVolumeReclaimPolicy)
		**out = **in
	}
	if in.VolumeBindingMode != nil {
		in, out := &in.VolumeBindingMode, &out.VolumeBindingMode
		*out = new(storagev1.VolumeBindingMode)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StorageClassConfig.
func (in *StorageClassConfig) DeepCopy() *StorageClassConfig {
	if in == nil {
		return nil
	}
	out := new(StorageClassConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SubnetSpec) DeepCopyInto(out *SubnetSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SubnetSpec.
func (in *SubnetSpec) DeepCopy() *SubnetSpec {
	if in == nil {
		return nil
	}
	out := new(SubnetSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in Subnets) DeepCopyInto(out *Subnets) {
	{
		in := &in
		*out = make(Subnets, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Subnets.
func (in Subnets) DeepCopy() Subnets {
	if in == nil {
		return nil
	}
	out := new(Subnets)
	in.DeepCopyInto(out)
	return *out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Taint) DeepCopyInto(out *Taint) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Taint.
func (in *Taint) DeepCopy() *Taint {
	if in == nil {
		return nil
	}
	out := new(Taint)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *User) DeepCopyInto(out *User) {
	*out = *in
	if in.SSHAuthorizedKeys != nil {
		in, out := &in.SSHAuthorizedKeys, &out.SSHAuthorizedKeys
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new User.
func (in *User) DeepCopy() *User {
	if in == nil {
		return nil
	}
	out := new(User)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VPC) DeepCopyInto(out *VPC) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VPC.
func (in *VPC) DeepCopy() *VPC {
	if in == nil {
		return nil
	}
	out := new(VPC)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ValuesReference) DeepCopyInto(out *ValuesReference) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ValuesReference.
func (in *ValuesReference) DeepCopy() *ValuesReference {
	if in == nil {
		return nil
	}
	out := new(ValuesReference)
	in.DeepCopyInto(out)
	return out
}
