# Copyright 2026 Nutanix. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

apiVersion: controlplane.cluster.x-k8s.io/v1beta1
kind: KubeadmControlPlaneTemplate
metadata:
  name: not-used
spec:
  template:
    spec:
      kubeadmConfigSpec:
        clusterConfiguration:
          controllerManager:
            extraArgs:
              tls-min-version: "VersionTLS12"
          scheduler:
            extraArgs:
              tls-min-version: "VersionTLS12"
