# Copyright 2024 D2iQ, Inc. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

---
# Starting in Kubernetes v1.29 the Kubelet no longer adds temporary addresses to the Node.
# See https://github.com/kubernetes/kubernetes/pull/121028
# This causes a deadlock with the AWS CCM and some CNI providers including Calico.
# The Calico Pods won't start until some addresses are assigned,
# but the AWS CCM that adds the addresses can't start until the Calico Pods are running.
# Using hostNetworking allows the AWS CCM to start before the Calico Pods.
# The upstream CAPA templates are also already using hostNetworking for the CCM Pods.
hostNetworking: true
