# Copyright 2025 Nutanix. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

version: v2.2.2
name: golangci-lint-kube-api-linter
plugins:
- module: 'sigs.k8s.io/kube-api-linter'
  version: v0.0.0-20250710131328-b566fe88b732
