openAPIV3Schema:
  description: Cluster configuration
  properties:
    addons:
      description: Cluster configuration
      properties:
        ccm:
          properties:
            credentials:
              description: A reference to the Secret for credential informationfor
                the target Prism Central instance
              properties:
                name:
                  description: The name of the Secret
                  type: string
              required:
              - name
              type: object
          type: object
        clusterAutoscaler:
          properties:
            strategy:
              description: Addon strategy used to deploy cluster-autoscaler to the
                management cluster,targeting the workload cluster.
              enum:
              - ClusterResourceSet
              - HelmAddon
              type: string
          required:
          - strategy
          type: object
        cni:
          properties:
            provider:
              description: CNI provider to deploy
              enum:
              - Calico
              - Cilium
              type: string
            strategy:
              description: Addon strategy used to deploy the CNI provider to the workload
                cluster
              enum:
              - ClusterResourceSet
              - HelmAddon
              type: string
          required:
          - provider
          - strategy
          type: object
        csi:
          properties:
            defaultStorage:
              description: 'A tuple of provider name and storage class '
              properties:
                providerName:
                  description: Name of the CSI Provider for the default storage class
                  enum:
                  - aws-ebs
                  - nutanix
                  type: string
                storageClassConfigName:
                  description: Name of storage class config in any of the provider
                    objects
                  type: string
              required:
              - providerName
              - storageClassConfigName
              type: object
            providers:
              items:
                properties:
                  credentials:
                    description: The reference to any secret used by the CSI Provider.
                    properties:
                      name:
                        type: string
                    type: object
                  name:
                    description: Name of the CSI Provider
                    enum:
                    - aws-ebs
                    - nutanix
                    type: string
                  storageClassConfig:
                    items:
                      properties:
                        allowExpansion:
                          default: false
                          description: If the storage class should allow volume expanding
                          type: boolean
                        name:
                          description: Name of storage class config.
                          type: string
                        parameters:
                          additionalProperties:
                            type: string
                          description: Parameters passed into the storage class object.
                          type: object
                        reclaimPolicy:
                          default: Delete
                          enum:
                          - Recycle
                          - Delete
                          - Retain
                          type: string
                        volumeBindingMode:
                          default: WaitForFirstConsumer
                          enum:
                          - Immediate
                          - WaitForFirstConsumer
                          type: string
                      required:
                      - name
                      type: object
                    type: array
                  strategy:
                    description: Addon strategy used to deploy the CSI provider to
                      the workload cluster
                    enum:
                    - ClusterResourceSet
                    - HelmAddon
                    type: string
                required:
                - name
                - strategy
                type: object
              type: array
          type: object
        nfd:
          properties:
            strategy:
              description: Addon strategy used to deploy Node Feature Discovery (NFD)
                to the workload cluster
              enum:
              - ClusterResourceSet
              - HelmAddon
              type: string
          required:
          - strategy
          type: object
      type: object
    controlPlane:
      description: Node configuration
      properties:
        nutanix:
          description: Nutanix Node configuration
          properties:
            machineDetails:
              description: Nutanix Machine configuration
              properties:
                additionalCategories:
                  description: List of categories that need to be added to the machines.
                    Categories must already exist in Prism Central. One category key
                    can have more than one value.
                  items:
                    description: Nutanix Category Identifier
                    properties:
                      key:
                        description: key is the Key of category in PC.
                        type: string
                      value:
                        description: value is the category value linked to the category
                          key in PC.
                        type: string
                    type: object
                  type: array
                bootType:
                  description: NutanixBootType is an enumeration of different boot
                    types.
                  enum:
                  - legacy
                  - uefi
                  type: string
                cluster:
                  description: Nutanix Resource Identifier
                  properties:
                    name:
                      description: name is the resource name in the PC.
                      type: string
                    type:
                      description: NutanixIdentifierType is an enumeration of different
                        resource identifier types
                      enum:
                      - uuid
                      - name
                      type: string
                    uuid:
                      description: uuid is the UUID of the resource in the PC.
                      type: string
                  type: object
                image:
                  description: Nutanix Resource Identifier
                  properties:
                    name:
                      description: name is the resource name in the PC.
                      type: string
                    type:
                      description: NutanixIdentifierType is an enumeration of different
                        resource identifier types
                      enum:
                      - uuid
                      - name
                      type: string
                    uuid:
                      description: uuid is the UUID of the resource in the PC.
                      type: string
                  type: object
                memorySize:
                  description: memorySize is the memory size (in Quantity format)
                    of the VM eg. 4Gi
                  type: string
                subnets:
                  description: subnets is a list of network subnets to use for the
                    machine
                  items:
                    description: Nutanix Resource Identifier
                    properties:
                      name:
                        description: name is the resource name in the PC.
                        type: string
                      type:
                        description: NutanixIdentifierType is an enumeration of different
                          resource identifier types
                        enum:
                        - uuid
                        - name
                        type: string
                      uuid:
                        description: uuid is the UUID of the resource in the PC.
                        type: string
                    type: object
                  type: array
                systemDiskSize:
                  description: systemDiskSize is size (in Quantity format) of the
                    system disk of the VM eg. 20Gi
                  type: string
                vcpuSockets:
                  description: vcpuSockets is the number of vCPU sockets of the VM
                  type: integer
                vcpusPerSocket:
                  description: vcpusPerSocket is the number of vCPUs per socket of
                    the VM
                  type: integer
              required:
              - vcpusPerSocket
              - vcpuSockets
              - memorySize
              - image
              - cluster
              - subnets
              - systemDiskSize
              type: object
          required:
          - machineDetails
          type: object
      type: object
    etcd:
      properties:
        image:
          properties:
            repository:
              description: Image repository to pull from.
              pattern: ^((?:[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*|\[(?:[a-fA-F0-9:]+)\])(:[0-9]+)?/)?[a-z0-9]+((?:[._]|__|[-]+)[a-z0-9]+)*(/[a-z0-9]+((?:[._]|__|[-]+)[a-z0-9]+)*)*$
              type: string
            tag:
              description: Image tag to use.
              pattern: ^[\w][\w.-]{0,127}$
              type: string
          type: object
      type: object
    extraAPIServerCertSANs:
      description: Subject Alternative Names for the API Server signing cert. For
        Docker localhost,127.0.0.1,0.0.0.0,host.docker.internal are injected automatically.
        For Nutanix localhost,127.0.0.1,0.0.0.0 are injected automatically.
      items:
        pattern: ^[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*$
        type: string
      type: array
      uniqueItems: true
    globalImageRegistryMirror:
      properties:
        credentials:
          properties:
            secretRef:
              description: A reference to the Secret containing the registry credentials
                and optional CA certificate. The Secret should have keys 'username',
                'password' and optional 'ca.crt'. This credentials Secret is not required
                for some registries, e.g. ECR.
              properties:
                name:
                  description: The name of the Secret containing the registry credentials.
                    This Secret must exist in the same namespace as the Cluster.
                  type: string
              required:
              - name
              type: object
          type: object
        url:
          description: Registry mirror URL.
          format: uri
          pattern: ^https?://
          type: string
      required:
      - url
      type: object
    imageRegistries:
      description: Configuration for image registries.
      items:
        properties:
          credentials:
            properties:
              secretRef:
                description: A reference to the Secret containing the registry credentials
                  and optional CA certificate. The Secret should have keys 'username',
                  'password' and optional 'ca.crt'. This credentials Secret is not
                  required for some registries, e.g. ECR.
                properties:
                  name:
                    description: The name of the Secret containing the registry credentials.
                      This Secret must exist in the same namespace as the Cluster.
                    type: string
                required:
                - name
                type: object
            type: object
          url:
            description: Registry URL.
            format: uri
            pattern: ^https?://
            type: string
        required:
        - url
        type: object
      type: array
    kubernetesImageRepository:
      description: Sets the Kubernetes image repository used for the KubeadmControlPlane.
      pattern: ^((?:[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*|\[(?:[a-fA-F0-9:]+)\])(:[0-9]+)?/)?[a-z0-9]+((?:[._]|__|[-]+)[a-z0-9]+)*(/[a-z0-9]+((?:[._]|__|[-]+)[a-z0-9]+)*)*$
      type: string
    nutanix:
      description: Nutanix cluster configuration
      properties:
        controlPlaneEndpoint:
          description: Kubernetes control-plane endpoint configuration
          properties:
            host:
              description: host ip/fqdn for control plane API Server
              minLength: 1
              type: string
            port:
              default: 6443
              description: port for control plane API Server
              maximum: 65535
              minimum: 1
              type: integer
          required:
          - host
          - port
          type: object
        prismCentralEndpoint:
          description: Nutanix Prism Central endpoint configuration
          properties:
            additionalTrustBundle:
              description: A base64 PEM encoded x509 cert for the RootCA that was
                used to create the certificate for a Prism Central that uses certificates
                that were issued by a non-publicly trusted RootCA.The trust bundle
                is added to the cert pool used to authenticate the TLS connection
                to the Prism Central.
              format: byte
              type: string
            credentials:
              description: A reference to the Secret for credential informationfor
                the target Prism Central instance
              properties:
                name:
                  description: The name of the Secret
                  type: string
              required:
              - name
              type: object
            insecure:
              description: Use insecure connection to Prism Central endpoint
              type: boolean
            url:
              description: The URL of Nutanix Prism Central, can be DNS name or an
                IP address
              format: uri
              minLength: 1
              pattern: ^https://
              type: string
          required:
          - url
          - credentials
          type: object
      type: object
    proxy:
      properties:
        additionalNo:
          description: 'Additional No Proxy list that will be added to the automatically
            calculated values required for cluster internal network. Default value:
            localhost,127.0.0.1,<POD_NETWORK>,<SERVICE_NETWORK>,kubernetes,kubernetes.default,.svc,.svc.<SERVICE_DOMAIN>'
          items:
            type: string
          type: array
        http:
          description: HTTP proxy value.
          type: string
        https:
          description: HTTPS proxy value.
          type: string
      type: object
    users:
      description: Users to add to the machine
      items:
        properties:
          hashedPassword:
            description: The hashed password for the user. Must be in the format of
              some hash function supported by the OS.
            type: string
          name:
            description: The username
            type: string
          sshAuthorizedKeys:
            description: A list of SSH authorized keys for this user
            items:
              type: string
            type: array
          sudo:
            description: The sudo rule that applies to this user
            type: string
        required:
        - name
        type: object
      type: array
  type: object
