apiVersion: cluster.x-k8s.io/v1beta1
kind: ClusterClass
metadata:
  labels:
    cluster.x-k8s.io/provider: eks
  name: eks-quick-start
spec:
  controlPlane:
    ref:
      apiVersion: controlplane.cluster.x-k8s.io/v1beta2
      kind: AWSManagedControlPlaneTemplate
      name: eks-quick-start-control-plane
  infrastructure:
    ref:
      apiVersion: infrastructure.cluster.x-k8s.io/v1beta2
      kind: AWSManagedClusterTemplate
      name: eks-quick-start
  patches:
  - external:
      discoverVariablesExtension: eksclusterconfigvars-dv.cluster-api-runtime-extensions-nutanix
      generateExtension: eksclusterv4configpatch-gp.cluster-api-runtime-extensions-nutanix
    name: cluster-config
  - external:
      discoverVariablesExtension: eksworkerconfigvars-dv.cluster-api-runtime-extensions-nutanix
      generateExtension: eksworkerv4configpatch-gp.cluster-api-runtime-extensions-nutanix
    name: worker-config
  workers:
    machineDeployments:
    - class: default-worker
      template:
        bootstrap:
          ref:
            apiVersion: bootstrap.cluster.x-k8s.io/v1beta2
            kind: EKSConfigTemplate
            name: quick-start-worker-configtemplate
        infrastructure:
          ref:
            apiVersion: infrastructure.cluster.x-k8s.io/v1beta2
            kind: AWSMachineTemplate
            name: eks-quick-start-worker-machinetemplate
---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta2
kind: AWSManagedClusterTemplate
metadata:
  labels:
    cluster.x-k8s.io/provider: eks
  name: eks-quick-start
spec:
  template:
    spec: {}
---
apiVersion: controlplane.cluster.x-k8s.io/v1beta2
kind: AWSManagedControlPlaneTemplate
metadata:
  labels:
    cluster.x-k8s.io/provider: eks
  name: eks-quick-start-control-plane
spec:
  template:
    spec:
      bootstrapSelfManagedAddons: false
      kubeProxy:
        disable: true
      vpcCni:
        disable: true
---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta2
kind: AWSMachineTemplate
metadata:
  labels:
    cluster.x-k8s.io/provider: eks
  name: eks-quick-start-worker-machinetemplate
spec:
  template:
    spec:
      ami:
        eksLookupType: AmazonLinux2023
      instanceMetadataOptions:
        httpPutResponseHopLimit: 2
        httpTokens: required
      instanceType: PLACEHOLDER
      sshKeyName: ""
---
apiVersion: bootstrap.cluster.x-k8s.io/v1beta2
kind: NodeadmConfigTemplate
metadata:
  labels:
    cluster.x-k8s.io/provider: eks
  name: eks-quick-start-worker-configtemplate
spec:
  template:
    spec: {}
