#!/usr/bin/env bash
set -euo pipefail
IFS=$'\n\t'

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
readonly SCRIPT_DIR

# shellcheck source=hack/common.sh
source "${SCRIPT_DIR}/../common.sh"
# shellcheck source=hack/addons/common.sh
source "${SCRIPT_DIR}/common.sh"

if [ -z "${AWS_EBS_CSI_CHART_VERSION:-}" ]; then
  echo "Missing environment variable: AWS_EBS_CSI_CHART_VERSION"
  exit 1
fi
if [ -z "${AWS_CSI_SNAPSHOT_CONTROLLER_VERSION:-}" ]; then
  echo "Missing environment variable: AWS_CSI_SNAPSHOT_CONTROLLER_VERSION"
  exit 1
fi

ASSETS_DIR="$(mktemp -d -p "${TMPDIR:-/tmp}")"
readonly ASSETS_DIR
trap_add "rm -rf ${ASSETS_DIR}" EXIT

readonly FILE_NAME="aws-ebs-csi.yaml"

readonly KUSTOMIZE_BASE_DIR="${SCRIPT_DIR}/kustomize/aws-ebs-csi"
mkdir -p "${ASSETS_DIR}/aws-ebs-csi"
envsubst -no-unset <"${KUSTOMIZE_BASE_DIR}/kustomization.yaml.tmpl" >"${ASSETS_DIR}/aws-ebs-csi/kustomization.yaml"
cp -r "${KUSTOMIZE_BASE_DIR}"/*.yaml "${ASSETS_DIR}/aws-ebs-csi/"

readonly EXTERNAL_SNAPSHOTTER_BASE_DIR="${SCRIPT_DIR}/kustomize/external-snapshotter"
mkdir -p "${ASSETS_DIR}/external-snapshotter"
envsubst -no-unset <"${EXTERNAL_SNAPSHOTTER_BASE_DIR}/kustomization.yaml.tmpl" >"${ASSETS_DIR}/external-snapshotter/kustomization.yaml"
cp -r "${EXTERNAL_SNAPSHOTTER_BASE_DIR}/overlays" "${ASSETS_DIR}/external-snapshotter/"

kustomize build --enable-helm "${ASSETS_DIR}/aws-ebs-csi/" >"${ASSETS_DIR}/${FILE_NAME}"

kubectl create configmap aws-ebs-csi --dry-run=client --output yaml \
  --from-file "${ASSETS_DIR}/${FILE_NAME}" \
  >"${ASSETS_DIR}/aws-ebs-csi-configmap.yaml"

# generate the list of images
readonly IMAGES_FILE="${GIT_REPO_ROOT}/charts/cluster-api-runtime-extensions-nutanix/templates/csi/aws-ebs/images.yaml"
images_file_from_configmap_yaml_manifest \
  "${ASSETS_DIR}/aws-ebs-csi-configmap.yaml" \
  "aws-ebs-csi" \
  "${AWS_EBS_CSI_CHART_VERSION}" \
  "${IMAGES_FILE}"
merge_images_file "${IMAGES_FILE}" "${GIT_REPO_ROOT}/addon-images.yaml"

# add warning not to edit file directly
cat <<EOF >"${GIT_REPO_ROOT}/charts/cluster-api-runtime-extensions-nutanix/templates/csi/aws-ebs/manifests/aws-ebs-csi-configmap.yaml"
$(cat "${GIT_REPO_ROOT}/hack/license-header.yaml.txt")

#=================================================================
#                 DO NOT EDIT THIS FILE
#  IT HAS BEEN GENERATED BY /hack/addons/update-aws-ebs-csi.sh
#=================================================================
$(cat "${ASSETS_DIR}/aws-ebs-csi-configmap.yaml")
EOF
