# Copyright 2024 Nutanix. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

image:
  tag: v${NODE_FEATURE_DISCOVERY_VERSION}-minimal
master:
  extraLabelNs:
    - nvidia.com
    - beta.amd.com
    - amd.com

worker: ### <NFD-WORKER-CONF-START-DO-NOT-REMOVE>
  config:
    sources:
      pci:
        deviceLabelFields:
          - "class"
          - "vendor"
  tolerations:
    - effect: NoSchedule
      key: node-role.kubernetes.io/master
    - effect: NoSchedule
      key: node-role.kubernetes.io/control-plane
### <NFD-WORKER-CONF-END-DO-NOT-REMOVE>

gc:
  tolerations:
    - effect: NoSchedule
      key: node-role.kubernetes.io/master
    - effect: NoSchedule
      key: node-role.kubernetes.io/control-plane
