apiVersion: cluster.x-k8s.io/v1beta1
kind: Cluster
metadata:
  labels:
    cluster.x-k8s.io/provider: docker
  name: ${CLUSTER_NAME}
spec:
  clusterNetwork:
    pods:
      cidrBlocks:
      - ${POD_CIDR:-192.168.0.0/16}
    serviceDomain: ${SERVICE_DOMAIN:="cluster.local"}
    services:
      cidrBlocks:
      - ${SERVICE_CIDR:-10.128.0.0/12}
  topology:
    class: docker-quick-start
    controlPlane:
      metadata: {}
      replicas: ${CONTROL_PLANE_MACHINE_COUNT}
    variables:
    - name: clusterConfig
      value:
        addons:
          clusterAutoscaler:
            strategy: ClusterResourceSet
          cni:
            provider: Calico
            strategy: ClusterResourceSet
          cosi: {}
          csi:
            defaultStorage:
              provider: local-path
              storageClassConfig: default
            providers:
              local-path:
                storageClassConfigs:
                  default: {}
                strategy: ClusterResourceSet
            snapshotController:
              strategy: ClusterResourceSet
          nfd:
            strategy: ClusterResourceSet
          serviceLoadBalancer:
            configuration:
              addressRanges:
              - end: 198.18.1.10
                start: 198.18.1.1
              - end: 198.18.1.30
                start: 198.18.1.21
            provider: MetalLB
        dns:
          coreDNS: {}
        encryptionAtRest:
          providers:
          - aescbc: {}
    - name: workerConfig
      value: {}
    version: ${KUBERNETES_VERSION}
    workers:
      machineDeployments:
      - class: default-worker
        metadata:
          annotations:
            cluster.x-k8s.io/cluster-api-autoscaler-node-group-max-size: "${WORKER_MACHINE_COUNT}"
            cluster.x-k8s.io/cluster-api-autoscaler-node-group-min-size: "${WORKER_MACHINE_COUNT}"
        name: md-0
