apiVersion: cluster.x-k8s.io/v1beta1
kind: Cluster
metadata:
  annotations:
    preflight.cluster.caren.nutanix.com/skip: all
  labels:
    cluster.x-k8s.io/provider: eks
  name: ${CLUSTER_NAME}
spec:
  topology:
    class: eks-quick-start
    controlPlane: {}
    variables:
    - name: clusterConfig
      value:
        addons:
          clusterAutoscaler: {}
          cni:
            provider: Cilium
          csi:
            defaultStorage:
              provider: aws-ebs
              storageClassConfig: default
            providers:
              aws-ebs:
                storageClassConfigs:
                  default: {}
            snapshotController: {}
          ingress:
            provider: aws-lb-controller
          nfd: {}
        eks:
          region: us-west-2
        kubeProxy:
          mode: disabled
    version: ${KUBERNETES_VERSION}
    workers:
      machineDeployments:
      - class: default-worker
        metadata:
          annotations:
            cluster.x-k8s.io/cluster-api-autoscaler-node-group-max-size: "${WORKER_MACHINE_COUNT}"
            cluster.x-k8s.io/cluster-api-autoscaler-node-group-min-size: "${WORKER_MACHINE_COUNT}"
        name: md-0
        variables:
          overrides:
          - name: workerConfig
            value:
              eks:
                instanceType: m5.2xlarge
