apiVersion: v1
kind: Secret
metadata:
  labels:
    cluster.x-k8s.io/provider: nutanix
  name: ${CLUSTER_NAME}-dockerhub-credentials
stringData:
  password: ${DOCKER_HUB_PASSWORD}
  username: ${DOCKER_HUB_USERNAME}
type: Opaque
---
apiVersion: v1
kind: Secret
metadata:
  labels:
    cluster.x-k8s.io/provider: nutanix
  name: ${CLUSTER_NAME}-pe-creds-for-csi
stringData:
  key: ${NUTANIX_PRISM_ELEMENT_ENDPOINT}:${NUTANIX_PORT}:${NUTANIX_USER}:${NUTANIX_PASSWORD}
---
apiVersion: v1
kind: Secret
metadata:
  labels:
    cluster.x-k8s.io/provider: nutanix
  name: ${CLUSTER_NAME}-pc-creds
stringData:
  credentials: |
    [
      {
        "type": "basic_auth",
        "data": {
          "prismCentral":{
            "username": "${NUTANIX_USER}",
            "password": "${NUTANIX_PASSWORD}"
          }
        }
      }
    ]
---
apiVersion: cluster.x-k8s.io/v1beta1
kind: Cluster
metadata:
  labels:
    cluster.x-k8s.io/cluster-name: ${CLUSTER_NAME}
    cluster.x-k8s.io/provider: nutanix
  name: ${CLUSTER_NAME}
spec:
  clusterNetwork:
    pods:
      cidrBlocks:
      - ${POD_CIDR:-192.168.0.0/16}
    serviceDomain: ${SERVICE_DOMAIN:="cluster.local"}
    services:
      cidrBlocks:
      - ${SERVICE_CIDR:-10.128.0.0/12}
  topology:
    class: nutanix-quick-start
    controlPlane:
      metadata: {}
      replicas: ${CONTROL_PLANE_MACHINE_COUNT}
    variables:
    - name: clusterConfig
      value:
        addons:
          ccm:
            credentials:
              name: ${CLUSTER_NAME}-pc-creds
          clusterAutoscaler:
            strategy: ClusterResourceSet
          cni:
            provider: Cilium
            strategy: ClusterResourceSet
          csi:
            defaultStorage:
              providerName: nutanix
              storageClassConfigName: nutanix-volume
            providers:
            - credentials:
                name: ${CLUSTER_NAME}-pe-creds-for-csi
              name: nutanix
              storageClassConfig:
              - name: nutanix-volume
                parameters:
                  storageContainer: ${NUTANIX_STORAGE_CONTAINER_NAME}
              strategy: HelmAddon
          nfd:
            strategy: ClusterResourceSet
        controlPlane:
          nutanix:
            machineDetails:
              bootType: legacy
              cluster:
                name: ${NUTANIX_PRISM_ELEMENT_CLUSTER_NAME}
                type: name
              image:
                name: ${NUTANIX_MACHINE_TEMPLATE_IMAGE_NAME}
                type: name
              memorySize: 4Gi
              subnets:
              - name: ${NUTANIX_SUBNET_NAME}
                type: name
              systemDiskSize: 40Gi
              vcpuSockets: 2
              vcpusPerSocket: 1
        imageRegistries:
        - credentials:
            secretRef:
              name: ${CLUSTER_NAME}-dockerhub-credentials
          url: https://docker.io
        nutanix:
          controlPlaneEndpoint:
            host: ${CONTROL_PLANE_ENDPOINT_IP}
            port: 6443
          prismCentralEndpoint:
            credentials:
              name: ${CLUSTER_NAME}-pc-creds
            insecure: ${NUTANIX_INSECURE}
            url: https://${NUTANIX_ENDPOINT}:9440
    - name: workerConfig
      value:
        nutanix:
          machineDetails:
            bootType: legacy
            cluster:
              name: ${NUTANIX_PRISM_ELEMENT_CLUSTER_NAME}
              type: name
            image:
              name: ${NUTANIX_MACHINE_TEMPLATE_IMAGE_NAME}
              type: name
            memorySize: 4Gi
            subnets:
            - name: ${NUTANIX_SUBNET_NAME}
              type: name
            systemDiskSize: 40Gi
            vcpuSockets: 2
            vcpusPerSocket: 1
    version: ${KUBERNETES_VERSION}
    workers:
      machineDeployments:
      - class: nutanix-quick-start-worker
        metadata:
          annotations:
            cluster.x-k8s.io/cluster-api-autoscaler-node-group-max-size: "${WORKER_MACHINE_COUNT}"
            cluster.x-k8s.io/cluster-api-autoscaler-node-group-min-size: "${WORKER_MACHINE_COUNT}"
        name: md-0
