apiVersion: v1
kind: Secret
metadata:
  labels:
    cluster.x-k8s.io/provider: nutanix
  name: ${CLUSTER_NAME}-dockerhub-credentials
stringData:
  password: ${DOCKER_HUB_PASSWORD}
  username: ${DOCKER_HUB_USERNAME}
type: Opaque
---
apiVersion: v1
kind: Secret
metadata:
  labels:
    cluster.x-k8s.io/provider: nutanix
  name: ${CLUSTER_NAME}-pc-creds-for-csi
stringData:
  key: ${NUTANIX_ENDPOINT}:${NUTANIX_PORT}:${NUTANIX_USER}:${NUTANIX_PASSWORD}
---
apiVersion: v1
kind: Secret
metadata:
  labels:
    cluster.x-k8s.io/provider: nutanix
  name: ${CLUSTER_NAME}-pc-creds
stringData:
  credentials: |
    [
      {
        "type": "basic_auth",
        "data": {
          "prismCentral":{
            "username": "${NUTANIX_USER}",
            "password": "${NUTANIX_PASSWORD}"
          }
        }
      }
    ]
---
apiVersion: cluster.x-k8s.io/v1beta1
kind: Cluster
metadata:
  labels:
    cluster.x-k8s.io/cluster-name: ${CLUSTER_NAME}
    cluster.x-k8s.io/provider: nutanix
  name: ${CLUSTER_NAME}
spec:
  clusterNetwork:
    pods:
      cidrBlocks:
      - ${POD_CIDR:-192.168.0.0/16}
    serviceDomain: ${SERVICE_DOMAIN:="cluster.local"}
    services:
      cidrBlocks:
      - ${SERVICE_CIDR:-10.128.0.0/12}
  topology:
    class: nutanix-quick-start
    controlPlane:
      metadata: {}
      replicas: ${CONTROL_PLANE_MACHINE_COUNT}
    variables:
    - name: clusterConfig
      value:
        addons:
          ccm:
            credentials:
              secretRef:
                name: ${CLUSTER_NAME}-pc-creds
            strategy: HelmAddon
          clusterAutoscaler: {}
          cni:
            provider: Calico
          csi:
            defaultStorage:
              provider: nutanix
              storageClassConfig: volume
            providers:
              nutanix:
                credentials:
                  secretRef:
                    name: ${CLUSTER_NAME}-pc-creds-for-csi
                storageClassConfigs:
                  volume:
                    parameters:
                      storageContainer: ${NUTANIX_STORAGE_CONTAINER_NAME}
                strategy: HelmAddon
            snapshotController:
              strategy: HelmAddon
          nfd: {}
          serviceLoadBalancer:
            configuration:
              addressRanges:
              - end: 198.18.1.10
                start: 198.18.1.1
              - end: 198.18.1.30
                start: 198.18.1.21
            provider: MetalLB
        controlPlane:
          nutanix:
            machineDetails:
              bootType: uefi
              cluster:
                name: ${NUTANIX_PRISM_ELEMENT_CLUSTER_NAME}
                type: name
              image:
                name: ${NUTANIX_MACHINE_TEMPLATE_IMAGE_NAME}
                type: name
              memorySize: 4Gi
              subnets:
              - name: ${NUTANIX_SUBNET_NAME}
                type: name
              systemDiskSize: 40Gi
              vcpuSockets: 2
              vcpusPerSocket: 1
        encryptionAtRest:
          providers:
          - aescbc: {}
        imageRegistries:
        - credentials:
            secretRef:
              name: ${CLUSTER_NAME}-dockerhub-credentials
          url: https://docker.io
        nutanix:
          controlPlaneEndpoint:
            host: ${CONTROL_PLANE_ENDPOINT_IP}
            port: 6443
            virtualIP:
              provider: KubeVIP
          prismCentralEndpoint:
            credentials:
              secretRef:
                name: ${CLUSTER_NAME}-pc-creds
            insecure: ${NUTANIX_INSECURE}
            url: https://${NUTANIX_ENDPOINT}:9440
    - name: workerConfig
      value:
        nutanix:
          machineDetails:
            bootType: uefi
            cluster:
              name: ${NUTANIX_PRISM_ELEMENT_CLUSTER_NAME}
              type: name
            image:
              name: ${NUTANIX_MACHINE_TEMPLATE_IMAGE_NAME}
              type: name
            memorySize: 4Gi
            subnets:
            - name: ${NUTANIX_SUBNET_NAME}
              type: name
            systemDiskSize: 40Gi
            vcpuSockets: 2
            vcpusPerSocket: 1
    version: ${KUBERNETES_VERSION}
    workers:
      machineDeployments:
      - class: default-worker
        metadata:
          annotations:
            cluster.x-k8s.io/cluster-api-autoscaler-node-group-max-size: "${WORKER_MACHINE_COUNT}"
            cluster.x-k8s.io/cluster-api-autoscaler-node-group-min-size: "${WORKER_MACHINE_COUNT}"
        name: md-0
