apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: NutanixFailureDomain
metadata:
  name: fd-1
spec:
  prismElementCluster:
    name: ${NUTANIX_PRISM_ELEMENT_CLUSTER_NAME}
    type: name
  subnets:
  - name: ${NUTANIX_SUBNET_NAME}
    type: name
---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: NutanixFailureDomain
metadata:
  name: fd-2
spec:
  prismElementCluster:
    name: ${NUTANIX_PRISM_ELEMENT_CLUSTER_NAME}
    type: name
  subnets:
  - name: ${NUTANIX_SUBNET_NAME}
    type: name
---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: NutanixFailureDomain
metadata:
  name: fd-3
spec:
  prismElementCluster:
    name: ${NUTANIX_PRISM_ELEMENT_CLUSTER_NAME}
    type: name
  subnets:
  - name: ${NUTANIX_SUBNET_NAME}
    type: name
---
apiVersion: v1
kind: Secret
metadata:
  labels:
    cluster.x-k8s.io/provider: nutanix
  name: ${CLUSTER_NAME}-dockerhub-credentials
stringData:
  password: ${DOCKER_HUB_PASSWORD}
  username: ${DOCKER_HUB_USERNAME}
type: Opaque
---
apiVersion: v1
kind: Secret
metadata:
  labels:
    cluster.x-k8s.io/provider: nutanix
  name: ${CLUSTER_NAME}-pc-creds-for-csi
stringData:
  key: ${NUTANIX_ENDPOINT}:${NUTANIX_PORT}:${NUTANIX_USER}:${NUTANIX_PASSWORD}
---
apiVersion: v1
kind: Secret
metadata:
  labels:
    cluster.x-k8s.io/provider: nutanix
  name: ${CLUSTER_NAME}-pc-creds
stringData:
  credentials: |
    [
      {
        "type": "basic_auth",
        "data": {
          "prismCentral":{
            "username": "${NUTANIX_USER}",
            "password": "${NUTANIX_PASSWORD}"
          }
        }
      }
    ]
---
apiVersion: cluster.x-k8s.io/v1beta1
kind: Cluster
metadata:
  labels:
    cluster.x-k8s.io/cluster-name: ${CLUSTER_NAME}
    cluster.x-k8s.io/provider: nutanix
  name: ${CLUSTER_NAME}
spec:
  clusterNetwork:
    pods:
      cidrBlocks:
      - ${POD_CIDR:-192.168.0.0/16}
    serviceDomain: ${SERVICE_DOMAIN:="cluster.local"}
    services:
      cidrBlocks:
      - ${SERVICE_CIDR:-10.128.0.0/12}
  topology:
    class: nutanix-quick-start
    controlPlane:
      metadata:
        annotations:
          controlplane.cluster.x-k8s.io/skip-kube-proxy: ""
      replicas: ${CONTROL_PLANE_MACHINE_COUNT}
    variables:
    - name: clusterConfig
      value:
        addons:
          ccm:
            credentials:
              secretRef:
                name: ${CLUSTER_NAME}-pc-creds
            strategy: HelmAddon
          clusterAutoscaler: {}
          cni:
            provider: Cilium
          cosi: {}
          k8sRegistrationAgent: {}
          csi:
            defaultStorage:
              provider: nutanix
              storageClassConfig: volume
            providers:
              nutanix:
                credentials:
                  secretRef:
                    name: ${CLUSTER_NAME}-pc-creds-for-csi
                storageClassConfigs:
                  volume:
                    parameters:
                      storageContainer: ${NUTANIX_STORAGE_CONTAINER_NAME}
                strategy: HelmAddon
            snapshotController:
              strategy: HelmAddon
          nfd: {}
          serviceLoadBalancer:
            configuration:
              addressRanges:
              - end: ${KUBERNETES_SERVICE_LOAD_BALANCER_IP}
                start: ${KUBERNETES_SERVICE_LOAD_BALANCER_IP}
            provider: MetalLB
        controlPlane:
          nutanix:
            failureDomains:
            - fd-1
            - fd-2
            - fd-3
            machineDetails:
              bootType: uefi
              imageLookup:
                baseOS: ${NUTANIX_MACHINE_TEMPLATE_BASE_OS}
                format: ${NUTANIX_MACHINE_TEMPLATE_LOOKUP_FORMAT}
              memorySize: 4Gi
              systemDiskSize: 40Gi
              vcpuSockets: 2
              vcpusPerSocket: 1
        dns:
          coreDNS: {}
        encryptionAtRest:
          providers:
          - aescbc: {}
        imageRegistries:
        - credentials:
            secretRef:
              name: ${CLUSTER_NAME}-dockerhub-credentials
          url: https://docker.io
        nutanix:
          controlPlaneEndpoint:
            host: ${CONTROL_PLANE_ENDPOINT_IP}
            port: 6443
            virtualIP:
              provider: KubeVIP
          prismCentralEndpoint:
            credentials:
              secretRef:
                name: ${CLUSTER_NAME}-pc-creds
            insecure: ${NUTANIX_INSECURE}
            url: https://${NUTANIX_ENDPOINT}:9440
    - name: workerConfig
      value:
        nutanix:
          machineDetails:
            bootType: uefi
            cluster:
              name: ${NUTANIX_PRISM_ELEMENT_CLUSTER_NAME}
              type: name
            imageLookup:
              baseOS: ${NUTANIX_MACHINE_TEMPLATE_BASE_OS}
              format: ${NUTANIX_MACHINE_TEMPLATE_LOOKUP_FORMAT}
            memorySize: 4Gi
            subnets:
            - name: ${NUTANIX_SUBNET_NAME}
              type: name
            systemDiskSize: 40Gi
            vcpuSockets: 2
            vcpusPerSocket: 1
    version: ${KUBERNETES_VERSION}
    workers:
      machineDeployments:
      - class: default-worker
        metadata:
          annotations:
            cluster.x-k8s.io/cluster-api-autoscaler-node-group-max-size: "${WORKER_MACHINE_COUNT}"
            cluster.x-k8s.io/cluster-api-autoscaler-node-group-min-size: "${WORKER_MACHINE_COUNT}"
        name: md-0
      - class: default-worker
        failureDomain: fd-3
        metadata:
          annotations:
            cluster.x-k8s.io/cluster-api-autoscaler-node-group-max-size: "${WORKER_MACHINE_COUNT}"
            cluster.x-k8s.io/cluster-api-autoscaler-node-group-min-size: "${WORKER_MACHINE_COUNT}"
        name: md-1
        variables:
          overrides:
          - name: workerConfig
            value:
              nutanix:
                machineDetails:
                  bootType: uefi
                  imageLookup:
                    baseOS: ${NUTANIX_MACHINE_TEMPLATE_BASE_OS}
                    format: ${NUTANIX_MACHINE_TEMPLATE_LOOKUP_FORMAT}
                  memorySize: 4Gi
                  systemDiskSize: 40Gi
                  vcpuSockets: 2
                  vcpusPerSocket: 1
