# Copyright 2023 D2iQ, Inc. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

---
apiVersion: v1
kind: Secret
metadata:
  name: ${CLUSTER_NAME}-dockerhub-credentials
stringData:
  username: ${DOCKER_HUB_USERNAME}
  password: ${DOCKER_HUB_PASSWORD}
type: Opaque
