# Copyright 2024 Nutanix. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

{{- if .Values.hooks.ccm.nutanix.helmAddonStrategy.defaultValueTemplateConfigMap.create }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: '{{ .Values.hooks.ccm.nutanix.helmAddonStrategy.defaultValueTemplateConfigMap.name }}'
data:
  values.yaml: |-
    ---
    prismCentralEndPoint: {{ `{{ .PrismCentralHost }}` }}
    prismCentralPort: {{ `{{ .PrismCentralPort }}` }}
    prismCentralInsecure: {{ `{{ .PrismCentralInsecure }}` }}
    {{ `{{- with .PrismCentralAdditionalTrustBundle }}` }}
    prismCentralAdditionalTrustBundle: {{ `{{ printf "%q" . }}` }}
    {{ `{{- end }}` }}

    # The Secret containing the credentials will be created by the handler.
    createSecret: false
    secretName: nutanix-ccm-credentials
{{- end -}}
