# Copyright 2023 Nutanix. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

name: conventional-release-labels
on:
  pull_request_target:
    types:
      - opened
      - edited
jobs:
  label:
    runs-on: ubuntu-22.04
    steps:
      - uses: bcoe/conventional-release-labels@v1
